#!/usr/bin/env bash

SCRIPT_PATH="$(realpath "$0")"
CURRENT_PID=$$
LOGGING=${1:-0}

pgrep -f "${SCRIPT_PATH}" | grep -v "^${CURRENT_PID}$" | xargs -r kill

SOCKET="/tmp/.now_playing_socket"
LOG_FILE="/tmp/.now_playing_socket.log"

function log() {
    if [[ $LOGGING -eq 1 ]]; then
        printf '%b\n' "$*" 1>&2 # Send log to stderr
        printf '%b\n' "$*" &>> "${LOG_FILE}"
    fi
}

function Exit() {
    local -i pid=$1
    if [[ -n "$pid" && "$pid" != "0" ]]; then
        kill -SIGTERM $pid && log "Killed pid '$pid'" || log "Failed to kill pid '$pid'"
    fi
    log "\nExiting... Bye!\n"
    exit $?
}

function CheckPlay() {
    local -i isPlaying=0
    local title=""
    local artist=""
    local album=""
    local combined=""

    PLAYERS=($(playerctl --list-all | tr '\n' ' ' 2> /dev/null))

    for player in "${PLAYERS[@]:-""}"; do
        status_="$(playerctl --player="${player}" status 2>/dev/null)"
        if [[ "${status_}" == "Playing" ]]; then

            title="$(playerctl --player="${player}" metadata title)"
            artist="$(playerctl --player="${player}" metadata artist)"
            album="$(playerctl --player="${player}" metadata album)"

            if [[ "${player}" == "spotify" ]]; then
                if [[ "${title}" == "Advertisement" ]]; then
                    pactl set-sink-mute @DEFAULT_SINK@ true
                else
                    pactl set-sink-mute @DEFAULT_SINK@ false
                fi
            fi

            [[ "${player}" == "mpv" ]] && title="${title%.*}"

            if [[ -n "${artist}" ]]; then
                combined="${artist} - ${title}"
            else
                combined="${title}"
            fi

            [[ -n "${album}" ]] && combined="${combined} (${album})"

            combined="$(echo "$combined" | sed \
                -e 's/\\/\\\\/g' \
                -e 's/"/\\"/g' \
                -e 's/\t/\\t/g' \
                -e 's/\r/\\r/g' \
                -e 's/\n/\\n/g' \
                -e 's/\f/\\f/g'
            )"

            log "You are playing: ${combined}"
            echo "{\"text\": \"${combined}\", \"class\": \"active\"}" | socat - UNIX-CONNECT:"${SOCKET}"
            isPlaying=1
            break
        else
            isPlaying=0
        fi
    done

    [[ $isPlaying -eq 0 ]] && {
        log "You are not playing anything"
        echo '{"text": "", "class": "inactive"}' | socat - UNIX-CONNECT:"${SOCKET}"
    }
}

function NowPlaying_Output() {
    rm -f "${SOCKET}" &> /dev/null
    while read -r line; do
        echo "${line}"
    done < <(socat -u UNIX-LISTEN:"${SOCKET}",fork -)
}

function main() {
    NowPlaying_Output &
    local -i now_playing_pid=$!
    [[ -z "$now_playing_pid" ]] && return 1 || true
    trap 'Exit $now_playing_pid' EXIT SIGINT SIGTERM
    while true; do
        CheckPlay
        sleep 0.3
    done
}

main "${@}"

