#!/bin/bash

declare -a ARG_ARR
declare -a SUDO

RUN_WITH_SUDO="sudo"

ARG_ARR=("$@")
SUDO=("${RUN_WITH_SUDO}" " ")

INSTALL=0

function LOG() {
    local -g type_="$1"
    local -g color="" nc="\033[0m" green="\033[38;2;10;244;10m" \
        dark_red="\033[38;2;255;0;0m" red="\033[38;2;200;10;100m"

    shift
    case ${type_} in
        info) color="${green}" ;;
        error) color="${red}" ;;
        fatal) color="${dark_red}";;
    esac
    printf '[%b%s%b]: %s\n' "${color}" "${type_}" "${nc}" "${*}"
    [[ "${type_}" == "fatal" ]] && exit 1
}

function Install() {
    local msg="$1"; shift 1
    declare -a packages=("$@")
    LOG info "====================${msg}===================="
    if [[ $INSTALL -eq 1 ]]; then
        if ${SUDO[@]}pacman --noconfirm --needed -S ${packages[@]}; then
            LOG info "Success fully installed: ${packages[@]}"
        else
            LOG error "Errors encoutered while installing"
        fi
    else
        printf '%s\n' "pacman -S --noconfirm ${packages[@]}"
    fi
}

for ((i=0;i<${#ARG_ARR[@]};i++)); do
    arg="${ARG_ARR[$i]}"
    case "${arg}" in
        --install) INSTALL=1 ;;
        -i) INSTALL=1 ;;
    esac
done

printf '%b\n' "\n##############    Installing dependencies for Sway    ##############\n"

# Core Wayland + Sway tools
Install "Installing Core Wayland + Sway tools" sway swaylock swayidle hyprlock foot waybar xdg-utils

# Utilities
Install "Installing extra Utilities" grim slurp wf-recorder brightnessctl playerctl libnotify bc mako

# Audio & Volume
Install "Installing Audio & Volume" pipewire pipewire-pulse pavucontrol mpv mpv-mpris ffmpeg

# File manager & terminal
Install "Installing File manager & terminal" dolphin konsole foot alacritty

# System monitor
Install "Installing System monitor" htop btop atop ctop plasma-systemmonitor

# Rofi/Wofi launchers
Install "Installing Rofi/Wofi launchers" rofi fuzzel wofi rofi-emoji

# Browsers
Install "Installing Browser" qutebrowser

# Text-based visualizer
Install "Installing Text-based visualizer" cava figlet cowsay

# autotiling
Install "Installing Python i3ipc for autotiling" autotiling

printf '%s\n' "Maybe installed"

