#!/usr/bin/env bash

set -euo pipefail

# Global readonly vars
readonly THIS_SCRIPT_NAME="${0##*/}"
readonly JOURNAL_DIR="${HOME}/journalDir"
readonly TEMPLATE_FILE="${JOURNAL_DIR}/.template"
readonly F_TRANSFORM_KEY_FILE="${HOME}/.config/custom/${THIS_SCRIPT_NAME}/substitution_cipher"

# Global mutable vars
TEMP_FILE="" TMP=""
NO_COLOR=1
VERBOSE=0
JOURNAL_FILE="${JOURNAL_DIR}/logs/$(date +%Y-%m-%d_).md"
TRANSFORM_KEY=""

function log() {
    local _type="${1}"; shift 1
    local mark="" _color=""
    case "${_type}" in
        error) _color="${RED}" mark="!";;
        info) _color="${GREEN}" mark="*" ;;
    esac
    case "${_type}" in
        debug) [[ $VERBOSE -eq 0 ]] || \
            printf "[%b%s%b]: %b\n" "${_color}" "${_type}${mark}" "${NC}" "${*}" ;;
        *) printf "[%b%s%b]: %b\n" "${_color}" "${_type}${mark}" "${NC}" "${*}" ;;
    esac
}

function SetColors() {
    RED=""
    GREEN=""
    BLUE=""
    LIGHT_GREEN=""
    MUDDY=""
    NC=""
    export RED GREEN BLUE \
        LIGHT_GREEN MUDDY NC
    is_flag_enabled "$NO_COLOR" && return 0
    RED="\033[38;2;159;29;75m"
    GREEN="\033[38;2;108;176;97m"
    BLUE="\033[38;2;103;128;229m"
    LIGHT_GREEN="\033[38;2;115;202;97m"
    MUDDY="\033[38;2;181;191;121m"
    NC="\033[0m"
}

function ShowUsage() {
    printf "%b\n" \
        "" \
        " ${GREEN}Usage:${NC} JournalToday [OPTIONS] [EDITOR]" \
        "" \
        " ${MUDDY}Options:${NC}" \
        "   ${GREEN}-s, --show${NC}             Show current journal" \
        "   ${GREEN}-e, --edit${NC}             Edit current journal" \
        "   ${GREEN}-t, --edit-template${NC}    Edit current journal template" \
        "   ${GREEN}-j, --journal${NC}          Specify a journal file" \
        "   ${GREEN}-r, --review${NC}           Intaractive Review mode (using pager)" \
        "   ${GREEN}-v, --verbose${NC}          Verbose mode on" \
        "   ${GREEN}-h, --help${NC}             Show this" \
        "" \
        " ${MUDDY}EDITORs:${NC}" \
        "   ${GREEN}vim | nvim | nano | micro${NC}   Edit journal using one of these" \
        ""
}

function require_var() {
    local var="${1:-""}" _type="${2:-""}" msg="${3:-""}"
    [[ -n "${var}" ]] && return 0
    [[ -n "${msg}" ]] && log "${_type}" "${msg}"
    return 1
}

function require_file() {
    local file="${1}" _type="${2:-""}" msg="${3:-""}"
    [[ -s "${file}" && -f "${file}" ]] && return 0
    [[ -n "${msg}" ]] && log "${_type}" "${msg}"
    return 1
}

function is_flag_enabled() {
    local -i var=${1}
    [[ "$var" -eq 1 ]] && return 0
    return 1
}

function are_flags_enabled() {
    local -a flags=("${@}")
    for flag in "${flags[@]}"; do
        is_flag_enabled "${flag}" && continue
        return 1
    done
    return 0
}

function is_flag_disabled() {
    local -i var=${1}
    [[ "$var" -eq 0 ]] && return 0
    return 1
}

function ColorPath() {
    printf '%b' "${BLUE}${1//$HOME/\~}${NC}"
}

function CreateNewKey() {
    local key="" abc=""
    key="$(printf '%s\n' {{A..Z},{a..z}} | shuf | tr -d '\n' )"
    abc="$(printf '%s\n' {{A..Z},{a..z}} | tr -d '\n')"
    local -r new_key="$(printf "%s -> %s\n" "${key}" "${abc}")"
    if [[ -n "${new_key}" ]]; then
        printf '%s\n' "${new_key}" 1> "${F_TRANSFORM_KEY_FILE}" && \
            log info "New key saved at '$(ColorPath "${F_TRANSFORM_KEY_FILE}")'"
        cp "${F_TRANSFORM_KEY_FILE}" "${F_TRANSFORM_KEY_FILE}.bak"
        TRANSFORM_KEY="$(cut -d' ' -f1 "${F_TRANSFORM_KEY_FILE}")"
    else
        log error "Failed to create new key"
    fi
}

function EncodeTextFile() {
    local FILE1="${1}" # Plain text file (no substitution cipher)
    local FILE2="${2}" # The journal file
    [[ -n "${FILE1}" ]] || { log error "${FUNCNAME[0]}: '\${FILE1}' is empty"; return 1; }
    [[ -n "${FILE2}" ]] || { log error "${FUNCNAME[0]}: '\${FILE2}' is empty"; return 1; }
    # fill FILE2 from readable text ==> Gibrish
    log debug "Applying Substitution cipher '$(ColorPath "${FILE1}")' ==> '$(ColorPath "${FILE2}")'"
    tr 'A-Za-z' "${TRANSFORM_KEY}" < "${FILE1}" > "${FILE2}"
}

function DecodeTextFile() {
    local FILE1="${1}" # substitution cipher encoded file
    local FILE2="${2}" # Temporary file
    [[ -n "${FILE1}" ]] || { log error "${FUNCNAME[0]}: '\${FILE1}' is empty"; return 1; }
    [[ -n "${FILE2}" ]] || { log error "${FUNCNAME[0]}: '\${FILE2}' is empty"; return 1; }
    # Fill FILE2 from Gibrish ==> readable text
    log debug "Reverting Substitution cipher '$(ColorPath "${FILE1}")' ==> '$(ColorPath "${FILE2}")'"
    tr "${TRANSFORM_KEY}" 'A-Za-z' < "${FILE1}" > "${FILE2}"
}

function Cleanup() {
    if require_file "${TEMP_FILE}"; then
        EncodeTextFile "${TEMP_FILE}" "${JOURNAL_FILE}"
        rm -f "${TEMP_FILE}" &> /dev/null || true
    fi
    log debug "Temporary file cleaned '$(ColorPath "${TEMP_FILE}")'"
}

function ShowJournal() {
    local KEY=""
    local -a bat_cmd_args=(
        "--language=markdown"
        "--paging=never"
        "--decorations=never"
        "--color=always"
    )

    require_file "${JOURNAL_FILE}" || \
        { log error "journal file '${JOURNAL_FILE}' doesn't exist"; return 1; }

    if require_file "${TRANSFORM_KEY}"; then
        KEY="$(cut -d' ' -f1 "${TRANSFORM_KEY}")"
    else
        KEY="${TRANSFORM_KEY}"
    fi
    [[ -n "${KEY}" ]] || { log error "No keys?"; return 1; }
    log info "File: '${JOURNAL_FILE}'\n"

    if grep -q "^# Date:" <(head -n1 "${JOURNAL_FILE}" | tr "${KEY}" 'A-Za-z'); then
        if command -v bat &> /dev/null; then
            bat "${bat_cmd_args[@]}" <(tr "${KEY}" 'A-Za-z' < "${JOURNAL_FILE}")
            return $?
        else
            tr "${KEY}" 'A-Za-z' < "${JOURNAL_FILE}"
        fi
    else
        if command -v bat &> /dev/null; then
            bat "${bat_cmd_args[@]}" "${JOURNAL_FILE}"
            return $?
        else
            cat "${JOURNAL_FILE}"
        fi
    fi
    log debug "Process completed, exiting..."
}

function ShowTemplate() {
    echo && log info "Template: $(ColorPath "${TEMPLATE_FILE}")\n"
    local should_color="never"
    is_flag_disabled "$NO_COLOR" && \
        should_color="always"
    if command -v bat &> /dev/null; then
        local -a cmd_args=(
            "--language=markdown"
            "--paging=never"
            "--decorations=never"
            "--color=${should_color}"
        )
        bat "${cmd_args[@]}" "${TEMPLATE_FILE}"
    else
        cat "${TEMPLATE_FILE}"
    fi
    log debug "Process completed, exiting..."
}

function EditTemplate() {
    local BACKUP="" temp_file=""
    BACKUP="${TEMPLATE_FILE}.bak"
    temp_file="$(mktemp -t template.XXXX)"

    log info "Edit template: $(ColorPath "${TEMPLATE_FILE}")"
    cp "${TEMPLATE_FILE}" "${temp_file}"
    "${EDITOR:-"vim"}" "${temp_file}"

    cmp -s "${TEMPLATE_FILE}" "${temp_file}" && \
        { log info "No changes made"; return 0; }

    log info "New changes:"
    diff --color=auto "${TEMPLATE_FILE}" "${temp_file}" || true
    log info "Copying last changes: ${LIGHT_GREEN}${TEMPLATE_FILE}${NC}" \
        "==> $(ColorPath "${BACKUP}")"
    cp "${TEMPLATE_FILE}" "${BACKUP}"
    mv "${temp_file}" "${TEMPLATE_FILE}"
    require_file "${temp_file}" && rm -f "${temp_file}"
}

function WriteDefaultTemplate() {
    local template_file="${1}"
    cat > "${template_file}" << EOF
# \$(date +'Date: %F, Created on: %T')
# vim: filetype=confini

## Intent
=> (one-line mission)

## Deep Work
=> (focused task)
=> (optional second block)

## Tasks
+ [ ] # (id) — (description) ( (time)h )
+ [ ] # (id) — (description) ( (time)h )
+ [ ] # (id) — (description) ( (time)h )
+ [ ] # (id) — (description) ( (time)h )

## Learning
+ [ ] # (cards) | (vocab / grammar)
+ [ ] # (min) | (practice topic)
+ [ ] # (concept review)

## Checklist
+ [ ] # (sync notes)
+ [ ] # (lint / test)
+ [ ] # (commit)
+ [ ] # (push)
+ [ ] # (update docs)

## Blockers
=> # ()
=> # ()

## Debug / Rant log
=> (paste errors, logs, thoughts)

## TIL
=> (command / pattern / insight)

## EOD
> [DONE]    :# (what shipped)
> [BLOCK]   :# (what stopped)
> [NEXT]    :# (tomorrow’s start)

EOF
}

function InteractiveReview() {
    cd "${JOURNAL_DIR}" || { log error "failed to enter '${JOURNAL_DIR}' journal directory"; return 1; }

    log info "Interactive review: Use Enter to select/view, 'r' to refresh list, 'q' to quit."

    while true; do
        local selected=""
        selected=$( \
            fzf \
            --height=50% \
            --border \
            --prompt="Select file: " \
        )

        if [[ -n "${selected}" ]]; then
            log info "Viewing: ${selected} (press 'q' in less to return, or Ctrl+C to force quit)"
            TMP="${JOURNAL_FILE}"
            JOURNAL_FILE="${JOURNAL_DIR}/${selected}"
            ShowJournal | less -c -
            JOURNAL_FILE="${TMP}"
            printf '\x1b[1A\x1b[2K'
        else
            log error "No file selected. Press 'r' to retry or 'q' to quit."
        fi

        if ! read -t 0.1 -n1 -r key; then
            key=""
        fi
        case "${key}" in
            q|Q) echo " Quitting."; return 0 ;;
            r|R) continue ;;
        esac
        printf '\n'
    done
}

function EditJournal() {
    TEMP_FILE="${JOURNAL_DIR}/.${JOURNAL_FILE##*/}.tmp"

    if [[ -n "${EDITOR}" ]]; then
        command -v "${EDITOR}" &> /dev/null || {
            log info "EDITOR '${EDITOR^}' not found faling back to vim"
            EDITOR="vim"
        }
    fi

    require_file "${TEMPLATE_FILE}" || {
        printf '%s\n' "Template here" > "${TEMPLATE_FILE}"
    }

    if ! require_file "${JOURNAL_FILE}"; then
        ### Fill the Journal with a template
        local cmd_output="" template_temp_file=""
        cmd_output="$(grep -Po '\$\(.*\)' "${TEMPLATE_FILE}" | sed 's@[\$\(\)]@@g' | sh || true)"
        template_temp_file="$(mktemp)"
        cp "${TEMPLATE_FILE}" "${template_temp_file}"
        sed -i "s@\$\(.*\)@${cmd_output}@g" "${template_temp_file}"
        EncodeTextFile "${template_temp_file}" "${JOURNAL_FILE}"
        rm -f "${template_temp_file}" || true
    fi

    log debug "Editor Initialized: ${EDITOR^}"
    if [[ "${EDITOR}" == "vim" ]]; then
        DecodeTextFile "${JOURNAL_FILE}" "${TEMP_FILE}"
        log debug "Edit temporary file '$(ColorPath "${TEMP_FILE}")'"
        sleep 0.01; vim -c 'colorscheme slate' "${TEMP_FILE}"
        Cleanup
    else
        DecodeTextFile "${JOURNAL_FILE}" "${TEMP_FILE}"
        log debug "Edit temporary file '$(ColorPath "${TEMP_FILE}")'"
        sleep 0.01; "${EDITOR:-"vim"}" "${TEMP_FILE}"
        Cleanup
    fi

    log debug "Process completed, exiting..."
}

function main() {
    local -a args=("$@")

    local -i edit_journal=0 edit_template=0 \
        show_journal=0 show_template=0 review_journal=0 \
            interactive_mode=0 override_no_color=0 override_color=0 \
                override_verbose=0 show_usage=0

    local editor="" journal_file=""

    SetColors

    local arg="" value=""
    for ((i=0;i<${#args[@]};i++)); do
        arg="${args[$i]}"
        [[ -n "${args[$((i+1))]:-""}" && "${args[$((i+1))]:-""}" != -* ]] && \
            value="${args[$((i+1))]:-""}" i=$((i+1))
        if [[ "${arg}" == *=* ]]; then
            IFS=$'=' read -r arg value <<< "${arg}"
            [[ -n "${value}" ]] || \
                { log error "'${arg}' requires a value"; return 1; }
        fi
        case "${arg}" in
            -e|-edit)               edit_journal=1;
                              require_var "${value}" && \
                              journal_file="${JOURNAL_DIR}/spls/${value}"       ;;
            --edit*template)        edit_template=1                             ;;
            --show*template)        show_template=1                             ;;
            nvim|vim|micro|nano)    edit_journal=1 editor="${arg}"              ;;
            --show*)                show_journal=1;
                                    require_var "${value}" && \
                                    journal_file="${JOURNAL_DIR}/spls/${value}" ;;
            -review*)               show_journal=1 review_journal=1             ;;
            -i|-interactive)        interactive_mode=1                          ;;
            --no-color)             override_no_color=1                         ;;
            -C|--color)             override_color=1                            ;;
            -v|--verbose)           override_verbose=1                          ;;
            -f|--journal)           journal_file="${JOURNAL_DIR}/spls/${value}" ;;
            -h|--help)              show_usage=1                                ;;
            -*)                     log error "Invalid argument: '${arg}'"      ;;
            *)
                require_file "${JOURNAL_DIR}/logs/${arg}" && \
                    { journal_file="${JOURNAL_DIR}/logs/${arg}"; continue; }
                require_file "${JOURNAL_DIR}/spls/${arg}" && \
                    { journal_file="${JOURNAL_DIR}/spls/${arg}"; continue; }
                log error "Journal doesn't exist: '${arg}'"
                ;;
        esac
    done

    trap 'Cleanup; exit 0' SIGTERM SIGINT

    [[ -t 1 ]] && NO_COLOR=0

    # Overrides
    is_flag_enabled "$override_no_color" && NO_COLOR=1
    is_flag_enabled "$override_color" && NO_COLOR=0
    is_flag_enabled "$override_verbose" && VERBOSE=1
    require_var "${journal_file}" && JOURNAL_FILE="${journal_file}"
    require_var "${editor}" && EDITOR="${editor}"

    # Set colors
    SetColors

    # Show usage
    is_flag_enabled "$show_usage" && \
        { ShowUsage; return 0; }

    mkdir -p "${JOURNAL_DIR}" "${F_TRANSFORM_KEY_FILE%/*}"

    # Write default template
    require_file "${TEMPLATE_FILE}" || \
        WriteDefaultTemplate "${TEMPLATE_FILE}"

    # Create keys if doesn't exist
    require_file "${F_TRANSFORM_KEY_FILE}" || \
        CreateNewKey

    require_file "${F_TRANSFORM_KEY_FILE}" && \
        TRANSFORM_KEY="$(cut -d' ' -f1 "${F_TRANSFORM_KEY_FILE}")"

    # Check keys first
    require_var "${TRANSFORM_KEY}" || \
        { log error "Transform_key is empty"; return 1; }

    # Show template
    is_flag_enabled "$show_template" && \
        { ShowTemplate; return 0; }

    # Review journal
    are_flags_enabled "$review_journal" \
        "$show_journal" && \
        { ShowJournal; return 0; }

    # Show journal
    is_flag_enabled "$show_journal" && \
        { ShowJournal; return 0; }

    # Interactive review
    is_flag_enabled "$interactive_mode" && \
        { InteractiveReview; return 0; }

    # Edit default template
    is_flag_enabled "$edit_template" && \
        { EditTemplate; return 0; }

    # Edit journal
    is_flag_enabled "$edit_journal" && \
        { EditJournal; return 0; }
}

main "${@}"

