#!/usr/bin/env bash

set -euo pipefail

# Default values for the service
if command -v "systemctl" &> /dev/null; then
    INIT_SYSTEM="systemd"
elif command -v "runit" &> /dev/null; then
    INIT_SYSTEM="runit"
fi

SCRIPT_NAME="$(readlink -f "${0}")"
SCRIPT_NAME="${SCRIPT_NAME##*/}"
CONFIG_FILE="/etc/${SCRIPT_NAME,,}"
DEFAULT_RYZENADJ_PATH="$(command -v ryzenadj)"

function log() {
    local type_="${1}"; shift 1
    if [[ "${type_}" == "error" ]]; then
        printf '[%b]: %b\n' "${type_}" "${*}" 1>&2
        return $?
    fi
    printf '[%b]: %b\n' "${type_}" "${*}"
}

# Usage of this script
function Usage() {
    printf '%b\n' \
        "Usage: ${SCRIPT_NAME} [OPTIONS]" \
        "" \
        "Desc: Create, update, and manage init (${INIT_SYSTEM}) service that applies a Ryzen power profile at boot" \
        "      using ryzenadj (AMD CPU only)." \
        "" \
        "Options:" \
        "  -a, -apply               Restart the init (${INIT_SYSTEM}) service (applies current profile)" \
        "  -n, -name=NAME           Service name (default: '${SCRIPT_NAME}')" \
        "  -l, -list                List available profiles and currently active profile" \
        "      -status              Show status of running profile" \
        "  -s, -set                 Set a profile in (${CONFIG_FILE}), conjunction with -p" \
        "  -p, -profile=PROFILE     Predefined profile for ${INIT_SYSTEM} system (default: balanced):" \
        "                             extreme_save, ultra_save, powersave, eco," \
        "                             balanced_low, balanced, stock, performance" \
        "                             or 'custom'" \
        "  -a, -args=ARGS           Custom ryzenadj arguments (required for 'custom';" \
        "                             overrides the selected profile)" \
        "  -r, -ryzenadj-path=PATH  Path to ryzenadj binary (default: ${DEFAULT_RYZENADJ_PATH})" \
        "  -i, -install             Install profile, without this script won't install" \
        "  -u, -uninstall           Uninstall the ${INIT_SYSTEM} service" \
        "  -c, -check               Check if the ${INIT_SYSTEM} service exists and is enabled" \
        "  -h, -help                Show this help message" \
        "" \
        "Examples:" \
        "  ${SCRIPT_NAME} -i -p performance                                        # Usually near OEM default" \
        "  ${SCRIPT_NAME} -i -p eco                                                # Efficient daily use" \
        "  ${SCRIPT_NAME} -i -p custom -a='--stapm-limit=65000 --max-performance'  # Custom args for ryzenadj" \
        "  ${SCRIPT_NAME} -u                                                       # Uninstall service" \
        "" \
        "" \
        "Available profiles:" \
        "   $(ListAvailableProfiles)"

    exit 0
}

function require_var() {
    local var="${1:-""}" _type="${2:-""}" msg="${3:-""}"
    [[ -n "${var}" ]] && return 0
    [[ -n "${msg}" ]] && log "${_type}" "${msg}"
    return 1
}

function require_file() {
    local file="${1}" _type="${2:-""}" msg="${3}"
    [[ -s "${file}" ]] && return 0
    [[ -n "${msg}" ]] && log "${_type}" "${msg}"
    return 1
}

function is_enabled() {
    local -i var=${1}
    [[ "$var" -eq 1 ]] && return 0
    return 1
}

function Install() {
    local src="${1:-""}" dest="${2:-""}"
    local owners="${3:-"root:root"}" mode="${4:-"644"}"
    local msg="${5:-""}"
    require_var "${dest}" error "Cannot install 'dest' var is empty"
    sudo mkdir -p "${dest%/*}"
    [[ -n "${src}" ]] && sudo mv "${src}" "${dest}"
    sudo chown "${owners}" "${dest}"
    if sudo chmod "${mode}" "${dest}"; then
        [[ -n "${msg}" ]] && { log info "${msg}"; return 0; }
    fi
}

function Install_POSIX_Script() {
    local file="${1}"
    local ryzenadj_path="${2}"
    local mode="${3:-"0755"}"
    local tmp_file=""
    tmp_file="$(mktemp)"
cat > "${tmp_file}" << EOF
#!/bin/env sh

exec 2>&1

make_worker() {
    script_name="\${1}"
    mode="\${2:-"0755"}"
    owners="\${3:-"root:root"}"
    cat 1> "\${script_name}" << EOF__
#!/bin/env sh

## Set a ryzen power profile at boot

## Available Ryzen profiles
extreme_save() {
    set -- "--stapm-limit=15000" "--fast-limit=18000" \\\\
        "--slow-limit=15000" "--apu-slow-limit=15000" \\\\
        "--vrm-current=30000" "--vrmmax-current=50000" \\\\
        "--tctl-temp=70" "--apu-skin-temp=30" \\\\
        "--dgpu-skin-temp=45" "--power-saving"
    printf "%s " "\\\${@}"
}

ultra_save() {
    set -- "--stapm-limit=20000" "--fast-limit=22000" \\\\
        "--slow-limit=20000" "--apu-slow-limit=20000" \\\\
        "--vrm-current=35000" "--vrmmax-current=60000" \\\\
        "--tctl-temp=75" "--apu-skin-temp=32" \\\\
        "--dgpu-skin-temp=48" "--power-saving"
    printf "%s " "\\\${@}"
}

powersave() {
    set -- "--stapm-limit=25000" "--fast-limit=28000" \\\\
        "--slow-limit=25000" "--apu-slow-limit=25000" \\\\
        "--vrm-current=38000" "--vrmmax-current=70000" \\\\
        "--tctl-temp=78" "--apu-skin-temp=34" \\\\
        "--dgpu-skin-temp=50" "--power-saving"
    printf "%s " "\\\${@}"
}

eco() {
    set -- "--stapm-limit=28000" "--fast-limit=30000" \\\\
        "--slow-limit=28000" "--apu-slow-limit=28000" \\\\
        "--vrm-current=40000" "--vrmmax-current=75000" \\\\
        "--tctl-temp=80" "--apu-skin-temp=36" \\\\
        "--dgpu-skin-temp=50" "--power-saving"
    printf "%s " "\\\${@}"
}

balanced_low() {
    set -- "--stapm-limit=32000" "--fast-limit=34000" \\\\
        "--slow-limit=32000" "--apu-slow-limit=32000" \\\\
        "--vrm-current=45000" "--vrmmax-current=80000" \\\\
        "--tctl-temp=84" "--apu-skin-temp=40" \\\\
        "--dgpu-skin-temp=52" "--power-saving"
    printf "%s " "\\\${@}"
}

balanced() {
    set -- "--stapm-limit=35000" "--fast-limit=40000" \\\\
        "--slow-limit=35000" "--apu-slow-limit=35000" \\\\
        "--vrm-current=50000" "--vrmmax-current=90000" \\\\
        "--tctl-temp=88" "--apu-skin-temp=45" \\\\
        "--dgpu-skin-temp=55" "--power-saving"
    printf "%s " "\\\${@}"
}

performance() {
    set -- "--stapm-limit=38000" "--fast-limit=48000" \\\\
    "--slow-limit=38000" "--apu-slow-limit=38000" \\\\
    "--vrm-current=60000" "--vrmmax-current=100000" \\\\
    "--tctl-temp=92" "--apu-skin-temp=50" \\\\
    "--dgpu-skin-temp=62"
    printf "%s " "\\\${@}"
}

stock() {
    set --
    printf "%s " "\\\${@}"
}

PROFILE="\\\${0##*/}"
PROFILE="\\\$(printf '%s\\\\n' "\\\$PROFILE" | grep -o "(.*)" | sed -e 's/[\\(\\)]//g')"
PROFILE="\\\${PROFILE:-"powersave"}"

# Set a profile from config file

# shellcheck disable=SC2046
set -- \\\$("\\\${PROFILE}")

${ryzenadj_path} "\\\${@}" || exit 1

tail -f /dev/null || sleep 8000000000

EOF__
    chown "\${owners}" "\${script_name}"
    chmod "\${mode}" "\${script_name}"
}

DEFAULT_PROFILE="${DEFAULT_PROFILE}"

CONFIG_FILE="${CONFIG_FILE}"

if [ ! -f "\${CONFIG_FILE}" ]; then
    cat 1> "\${CONFIG_FILE}" << EOL
#/usr/bin/env sh
# Default profile
PROFILE=\${DEFAULT_PROFILE}
EOL
fi

# Source config
# shellcheck disable=SC1090
. "\${CONFIG_FILE}"

[ -n "\${PROFILE}" ] || \\
    { printf '[error]: %s\n' "PROFILE missing from config file (\${CONFIG_FILE})"; exit 1; }

SHOULD_CONTINUE="0"
OLD_POWER_STATE="\$(cat /sys/class/power_supply/AC*/online)"
OLD_PROFILE="\${PROFILE}"
DIR="/tmp"

while :; do
    # Source configuration
    # shellcheck disable=SC1090
    . "\${CONFIG_FILE}"

    # New profile from config
    NEW_PROFILE="\${PROFILE}"
    # Live power state
    NEW_POWER_STATE="\$(cat /sys/class/power_supply/AC*/online)"
    # Dynamically named worker
    NEW_WORKER="RyzenProfile (\${PROFILE})"

    # Detect changes
    if [ "\${NEW_POWER_STATE}" = "\${OLD_POWER_STATE}" ] && \\
            [ "\${NEW_PROFILE}" = "\${OLD_PROFILE}" ] && \\
                [ "\${SHOULD_CONTINUE}" = "1" ]; then
        # Nothing changed - sleep and continue
        sleep 3 && continue
    fi

    # Log what's changed
    [ "\${NEW_POWER_STATE}" = "\${OLD_POWER_STATE}" ] || printf '[info]: %s\\n' "Power source is changed"
    [ "\${NEW_PROFILE}" = "\${OLD_PROFILE}" ] || printf '[info]: %s\\n' "Profile changed"

    # Log power source
    if [ "\${NEW_POWER_STATE}" = "1" ]; then
        printf '[info]: %s\\n' "Power source on AC"
    else
        printf '[info]: %s\\n' "Power source on BAT"
    fi

    # If OLD WORKER WAS alive
    if [ -n "\${OLD_WORKER_PID}" ]; then
        OLD_WORKER_NAME="\$(ps --no-headers -ocommand -p "\${OLD_WORKER_PID}")"
        kill -TERM "\${OLD_WORKER_PID}" && \
            printf '[info]: %s\\n' "Destroyed old worker (NAME: '\${OLD_WORKER_NAME}', PID: '\${OLD_WORKER_PID}')"
    fi

    [ -d "\${DIR}" ] || mkdir --mode=1777 "\${DIR}"

    # Create saint worker
    make_worker "\${DIR}/\${NEW_WORKER}" "0755" "root:root"

    # Run the worker
    cd "\${DIR}" || { printf '[error]: %s\\n' "Directory '\${DIR}' does not exist"; exit 1; }
    ./"\${NEW_WORKER}" &

    # Remeber old states for later comparison
    OLD_WORKER_PID="\$!"
    OLD_PROFILE="\${NEW_PROFILE}"
    OLD_POWER_STATE="\${NEW_POWER_STATE}"
    SHOULD_CONTINUE=1

    printf '[info]: %s\\n' "Created new worker (NAME: '\${NEW_WORKER}', PID: '\${OLD_WORKER_PID}')"

    # Remove the worker from disk
    sleep 0.6 && rm -f ./"\${NEW_WORKER}"

    # Pause for a momement
    sleep 3
done

EOF
    Install "${tmp_file}" "${file}" "root:root" "${mode}" "Successfully installed script '${file}'" || \
        { log error "Failed to install script"; return 1; }
}

function ListAvailableProfiles() {
    require_file "${POSIX_SCRIPT}" "" "" || { printf '%s\n' "Script not installed"; return 0; }
    grep -Eo '^[A-Za-z_].*\(\)[[:space:]]' "${POSIX_SCRIPT}" | sed 's/[\(\)]//g' | xargs
}

function ListProfiles() {
    require_file "${POSIX_SCRIPT}" error "Script '${POSIX_SCRIPT}' not installed" || true
    printf '%s\n' "Available Profiles (in '${POSIX_SCRIPT}'):"
    printf '  %s\n' "$(ListAvailableProfiles)"
    printf '%s\n' "Active config profile (in '${CONFIG_FILE}'):"
    printf '  %s\n' "$(grep -o '^PROFILE=.*' "${CONFIG_FILE}" | sed 's/PROFILE=//g')"
}

function ShowActive() {
    local pids=""
    local profile_cmd_string=""
    local -a pid_arr=()

    ps_pid() {
        pgrep -d, -f ".\/${SERVICE_NAME} \(.*\)" 2> /dev/null || \
        printf '%s\n' "no_pid"
    }

    pids="$(ps_pid)"

    [[ "${pids[0]}" == "no_pid" ]] && \
        { log error "Ryzen profile isn't applied or script not running"; return 1; }

    IFS=',' read -r -a pid_arr <<< "${pids}" || true

    printf '%s\n' "Running process (from 'ps --no-headers -o command -p $(ps_pid)' ):"

    for pid in "${pid_arr[@]}"; do
        profile_cmd_string="$(ps --no-headers -o command -p "${pid}" 2> /dev/null | \
            grep -o "${SERVICE_NAME} (.*)" || true)"
        if [[ "$(ps --no-headers -o ppid -p "${pid}" | tr -d ' ' || true)" != "1" ]]; then
            profile_cmd_string="'${profile_cmd_string}' [active (managed by '${SERVICE_UNIT_FILE}')]"
        else
            profile_cmd_string="'${profile_cmd_string}' [stale (disowned)]"
        fi
        printf "  %s => %s\n" "'${pid}'" "${profile_cmd_string}"
    done

    unset -f ps_pid
}

function KillStaleProcesses() {
    local pids=""
    local -a stale_pids=()
    local -a pid_arr=()

    ps_pid() {
        pgrep -d, -f ".\/${SERVICE_NAME} \(.*\)" 2> /dev/null || \
        printf '%s\n' "no_pid"
    }

    pids=$(ps_pid)

    [[ "${pids[0]}" == "no_pid" ]] && \
        { log error "Ryzen profile isn't applied or script not running"; return 1; }

    IFS=',' read -r -a pid_arr <<< "${pids}" || true

    for pid in "${pid_arr[@]}"; do
        [[ "$(ps --no-headers -o ppid -p "${pid}" | tr -d ' ' || true)" != "1" ]] && continue
        stale_pids+=("${pid}")
    done

    [[ ${#stale_pids[@]} -lt 1 ]] && { log warn "No stale process found"; return 0; }

    for pid in "${stale_pids[@]}"; do
        if sudo kill -SIGTERM "${pid}"; then
            log info "Killed stale pid: '${pid}'"
        else
            log error "Failed to kill stale pid: '${pid}'"
        fi
    done

    for pid in "${pid_arr[@]}"; do
        [[ "$(ps --no-headers -o ppid -p "${pid}" | tr -d ' ' || true)" != "1" ]] && continue
        if sudo kill -SIGTERM "${pid}"; then
            log info "Killed stale pid: '${pid}'"
        else
            log error "Failed to kill stale pid: '${pid}'"
        fi
    done

    unset -f ps_pid
}

function SetProfile() {
    require_var "${DEFAULT_PROFILE}" error "Default profile not set"

    require_file "${CONFIG_FILE}" "" "" || {
        local tmp_file=""
        tmp_file="$(mktemp)"
        cat > "${tmp_file}" << EOF
#/usr/bin/env sh
# Default profile
PROFILE=${DEFAULT_PROFILE}
EOF
        Install "${tmp_file}" "${CONFIG_FILE}" "root:root" "0644"
    }

    if sudo sed -i "/^PROFILE=.*/c\PROFILE=${DEFAULT_PROFILE}" "${CONFIG_FILE}"; then
        log info "Profile: '${DEFAULT_PROFILE}' set in Config: '${CONFIG_FILE}'"
    else
        log error "Failed to set '${DEFAULT_PROFILE}' in '${CONFIG_FILE}'"
    fi
}

# Function to create or update the systemd unit file
function Create_or_Update_systemd_unit() {
    local ryzenadj_path="${1}"
    local RyzenProfileScript="${2}"
    local tmp_file=""

    # Install script
    sudo mkdir -p "${RyzenProfileScript%/*}"
    Install_POSIX_Script "${RyzenProfileScript}" "${ryzenadj_path}"

    # Install systemd service
    tmp_file="$(mktemp)"
    cat > "${tmp_file}" << EOF
[Unit]
Description=RyzenProfil manager
After=multi-user.target

[Service]
ExecStart=${RyzenProfileScript}
Type=oneshot
Restart=on-failure
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target

EOF

    Install "${tmp_file}" "${SERVICE_UNIT_FILE}" "root:root" "0644" \
        "Systemd service '${SERVICE_UNIT_FILE}' installed" || \
        { log error "Failed to install systemd service (${SERVICE_UNIT_FILE})"; return 1; }
}

# Function to create or update the runit service file
function Create_or_Update_runit_unit() {
    local ryzenadj_path="${1}"
    local service_dir="${SERVICE_UNIT_FILE%/*}"
    local tmp_file=""

    # Create a POSIX script
    Install_POSIX_Script "${SERVICE_UNIT_FILE}" "${ryzenadj_path}"

    require_file "${SERVICE_UNIT_FILE}" error "Failed to install runit service (${SERVICE_UNIT_FILE})" && \
        log info "Runit service '${SERVICE_UNIT_FILE}' installed"

    tmp_file="$(mktemp)"

    cat > "${tmp_file}" << EOF
#!/bin/sh

exec vlogger -t ${SERVICE_NAME} -p daemon

EOF

    Install "${tmp_file}" "${service_dir}/log/run" "root:root" "0755" \
        "Successfully installed log service '${service_dir}/log/run'"
}

function Enable_runit_service() {
    sudo mkdir -p "/etc/sv/${SERVICE_NAME}"
    if [[ -L "/var/service" ]]; then
        sudo ln -sf "/etc/sv/${SERVICE_NAME}" "/var/service/" && \
            log info "service '${SERVICE_NAME}' enabled at boot"
    else
        sudo ln -sf "/etc/sv/${SERVICE_NAME}" "/etc/runit/runsvdir/current/" && \
            log info "service '${SERVICE_NAME}' enabled at boot"
    fi
}

# Function to uninstall the service
function Un_installsystemd_service() {
    if systemctl is-active --quiet "${SERVICE_NAME}"; then
        sudo systemctl stop "${SERVICE_NAME}" || { log warning "Failed to stop service."; }
    fi
    sudo systemctl disable "${SERVICE_NAME}" 2>/dev/null || { log warning "Failed to disable service."; }
    sudo rm -f "${SERVICE_UNIT_FILE}" || { log warning "Failed to remove unit file."; }
    sudo systemctl daemon-reload
    log info "Service ${SERVICE_NAME} uninstalled."
}

function Un_installrunit_service() {
    local service_dir=""
    [[ -L "/var/service" ]] && service_dir="/var/service" || service_dir="/etc/runit/runsvdir/current/"
    if sudo rm -f "${service_dir}/${SERVICE_NAME}" 2> /dev/null; then
        log info "Service '${SERVICE_NAME}' disabled at boot."
    else
        log error "Failed to disable '${SERVICE_NAME}' service."
    fi
    { sudo rm -r "/etc/sv/${SERVICE_NAME}" && log info "Uninstalled '${SERVICE_NAME}' service."; } || \
        log error "Failed to uninstall '${SERVICE_NAME}' service"
}

function Check_POSIX_sh() {
    local sh_shell=""
    command -v sh &> /dev/null && return 0
    create_symlink() {
        local src="${1}" target="${2:-"/usr/bin/sh"}"
        sudo mkdir -p "${target%/*}"
        sudo ln -svf "${src}" "${target}" || \
            log error "Failed to create symlink: '${src}' -> '${target}'"
    }
    for sh_shell in dash ash mksh yash ksh; do
        command -v "${sh_shell}" &> /dev/null && { create_symlink "${sh_shell}"; return 0; }
    done
    unset -f create_symlink
}

# Main function
function main() {
    local -a args=("${@}")
    local -i uninstall=0 install=0 check_service=0 set_profile=0
    local -i should_list_profiles=0 apply_profile=0
    local -i show_usage=0 show_status=0 kill_stale_processes=0
    local -g DEFAULT_PROFILE="balanced"
    local -g SERVICE_UNIT_FILE=""
    local -g POSIX_SCRIPT=""
    local -g SERVICE_NAME="${SCRIPT_NAME}"
    local ryzenadj_path="${DEFAULT_RYZENADJ_PATH}"

    # Argument parser
    local arg="" value=""
    for ((i=0;i<${#args[@]};i++)); do
        arg="${args[$i]}"
        [[ -n "${args[$((i+1))]:-""}" && "${args[$((i+1))]:-""}" != -* ]] && \
            value="${args[$((i+1))]:-""}" i=$((i+1))
        if [[ "${arg}" == *=* ]]; then
            IFS=$'=' read -r arg value <<< "${arg}"
            require_var "${value}" error "'${arg}' requires a value"
        fi
        [[ "${arg}" == --* ]] && arg="${arg//--/-}"
        case "${arg}" in
            -a|-apply)          apply_profile=1             ;;
            -n|-name)           SERVICE_NAME="${value}"     ;;
            -s|-set)            set_profile=1               ;;
            -p|-profile)        DEFAULT_PROFILE="${value}"  ;;
            -l|-list*|-show*)   should_list_profiles=1      ;;
            -status)            show_status=1               ;;
            -k|-kill*stale)     kill_stale_processes=1;;
            -r|-ryzenadj-path)  ryzenadj_path="${value}"    ;;
            -u|-uninstall)      uninstall=1                 ;;
            -i|-install)        install=1                   ;;
            -c|-check)          check_service=1             ;;
            -h|-help)           show_usage=1                ;;
            *) log error "Unknown option: '${arg}', use -help to see options"; return 1 ;;
        esac
    done

    if ! [[ -x "${ryzenadj_path}" ]]; then
        log error "Either 'ryzenadj' not found or not executable."
        log hint "Install it using your package manager or use --ryzenadj-path if it's somewhere outside PATH variable."
        return 1
    fi

    log info "Init system: '${INIT_SYSTEM}'"

    is_enabled "$set_profile" && SetProfile

    Check_POSIX_sh

    if [[ "${INIT_SYSTEM}" == "systemd" ]]; then
        SERVICE_UNIT_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
        POSIX_SCRIPT="/usr/local/bin/${SCRIPT_NAME}"

        is_enabled "$show_usage" && Usage

        # List the available profiles in POSIX script
        is_enabled "$should_list_profiles" && ListProfiles

        # Show active profile
        is_enabled "$show_status" && ShowActive

        # Check service status
        if [[ "${check_service}" -eq 1 ]]; then
            if systemctl is-enabled --quiet "${SERVICE_NAME}"; then
                log info "Service ${SERVICE_NAME} is enabled."
                systemctl status "${SERVICE_NAME}" --no-pager
            else
                log info "Service ${SERVICE_NAME} is not installed or enabled."
            fi
        fi

        # Apply profile immediately
        is_enabled "$apply_profile" && \
            { sudo systemctl restart "${SERVICE_NAME}" && log info "Successfully restarted service"; }

        # Uninstall service if requested
        is_enabled "$uninstall" && \
            { Un_installsystemd_service; return 0; }

        # Early return if not installing
        is_enabled "$install" || return 0

        # Create or update the systemd unit
        Create_or_Update_systemd_unit "${ryzenadj_path}" "${DEFAULT_PROFILE}"

        # Reload and enable
        sudo systemctl daemon-reload || { log error "Failed to reload systemd daemon."; return 1; }
        if sudo systemctl enable --now "${SERVICE_NAME}"; then
            log info "Service '${SERVICE_NAME}' enabled and started with profile '${DEFAULT_PROFILE}'."
        else
            log error "Failed to enable/start service: '${SERVICE_NAME}'"
        fi
    elif [[ "${INIT_SYSTEM}" == "runit" ]]; then
        SERVICE_UNIT_FILE="/etc/sv/${SERVICE_NAME}/run"
        POSIX_SCRIPT="${SERVICE_UNIT_FILE}"

        # Show usage
        is_enabled "$show_usage" && Usage

        # Show active profile
        is_enabled "$show_status" && ShowActive

        is_enabled "$kill_stale_processes" && KillStaleProcesses

        # List the available profiles in POSIX script
        is_enabled "$should_list_profiles" && ListProfiles

        # Check service status
        if is_enabled "$check_service"; then
            if sudo sv status "${SERVICE_NAME}"; then
                log info "Service ${SERVICE_NAME} is enabled."
            else
                log info "Service ${SERVICE_NAME} is not installed or enabled."
            fi
        fi

        # Apply profile immediately
        is_enabled "$apply_profile" && \
            { sudo sv restart "${SERVICE_NAME}"; log info "Successfully restarted service"; }

        # Uninstall service if requested
        is_enabled "${uninstall}" && \
            { Un_installrunit_service ; return 0; }

        # Early return if not installing
        is_enabled "$install" || return 0

        # Create or update the runit service
        Create_or_Update_runit_unit "${ryzenadj_path}"

        # Enable and start service
        Enable_runit_service
        sudo timeout -s SIGTERM 4s bash -c "while [[ ! -p \"/etc/sv/${SERVICE_NAME}/supervise/ok\" ]]; do :;done"
        if sudo sv restart "${SERVICE_NAME}"; then
            log info "Started '${SERVICE_NAME}'"
            log info "Check if profile is applied: use '${0##*/} -list' or use 'sudo ${ryzenadj_path} --info' verbose info"
        else
            log error "Failed to start '${SERVICE_NAME}'"
        fi
    else
        log error "Unknown init system"
    fi

}

main "$@"

