#!/usr/bin/env bash

set -euo pipefail

# Global Colors
HL="\033[1m"
NC="\033[0m"
MSG_COL="\033[38;2;255;240;200m"
BLUE="\033[38;2;116;112;218m"

# Log function
function log() {
    local _type="${1}"; shift
    local _color="" _t=""
    local -g info_color="\033[38;2;85;255;126m" \
        warn_color="\033[38;2;255;170;10m" \
        error_color="\033[38;2;244;29;31m" \
        fatal_color="\033[5m\033[38;2;255;0;0m" \
        other_color="\033[38;2;251;255;208m" \
        nc="\033[0m"
    case "${_type}" in
        info) _color="${info_color}" _t="*" ;;
        warn) _color="${warn_color}" _t="^" ;;
        error) _color="${error_color}" _t="!" ;;
        fatal) _color="${fatal_color}" _t="#" ;;
        *) _color="${other_color}" _t="" ;;
    esac

    printf "[%b%s%b%s]: %b\n" "${_color}" "${_type}" "${nc}" "${_t}" "${*}"
}


# Usage message
function Usage() {
    local config_file="${1}"
    local script_basename="${0##*/}"
    printf '\n%b\n' "${HL}Usage${NC}: ${script_basename} [boot] [options] <profile1> <profile2> ...\n"
    printf "  ${MSG_COL}%-18b${NC} %b\n" \
        "boot"              "Boot from ISO + disk image" \
        "<profile>"         "Profile name (defined in $(ColorPath "${config_file}"))" \
        "-f, fullscreen"    "Enable fullscreen mode" \
        "-e, edit"          "Edit the profiles config file"

    printf '%b\n' "\n${HL}Other flags:${NC}\n"
    printf "  ${MSG_COL}%-18b${NC} %b\n" \
        "create-image"      "Create new disk image" \
        "format"            "Specify the disk format when creating a new image" \
        "new-profile"       "Add a new profile to $(ColorPath "${config_file}") configuration" \
        "write"             "Write the current arugment values to the configuration" \
        "comment"           "Provide a comment when creating a new profile" \
        "-h, help"          "Show this help message"

    printf '%b\n' "\n${HL}Examples:${NC}\n"
    printf "  %s\n     ${HL}%b${NC}\n" \
        "Start with disk only"          "${script_basename} my_profile" \
        "Boot with Disk + ISO"          "${script_basename} boot my_profile" \
        "Create new image"              "${script_basename} profile=my_profile create-new-image image_name raw 20G" \
        "Create new profile"            "${script_basename} create-profile my_profile iso=/path/to/ISO.iso img=/path/to/disk.img"
    printf '%s\n' ""
}

function load_profile() {
    local profile_name="${1}"
    local -n disk_img_=${2}
    local -n iso_img_=${3}
    local -n disk_format_=${4}
    local -n selected_profile=${profile_name}

    if ! declare -p "${profile_name}" 2> /dev/null | grep -q 'declare -a' ; then
        log fatal "Profile '${profile_name}' not found."
        return 1
    fi

    for n in "${selected_profile[@]}"; do
        [[ "${n}" != *=* ]] && { log error "invalid pair '${n}'"; return 1; }
        IFS=$'=' read -r key value <<< "${n}"
        case "${key}" in
            img) disk_img_="${value}" ;;
            iso) iso_img_="${value}" ;;
        esac
    done
    disk_format_="${disk_img_##*.}"
}

function EditConfigFile() {
    local file="$1"
    ${EDITOR:-vim} "${file}"
}

function ColorPath() {
    sed "s@${HOME}@${BLUE//\\/\\\\}~${NC//\\/\\\\}@g" <(printf "%s\n" "${1}")
}

function ListProfiles() {
    local config_file="$1"
    local -a available_profiles=""
    [[ -f "${config_file}" ]] || return 1
    log info "Available profiles in $(ColorPath "${CONFIG_DIR}"):"
    mapfile -t available_profiles < <(grep -o '^[A-Za-z_]*=(' "${config_file}" | sed 's/=(//')
    for (( i=0; i < ${#available_profiles[@]}; i++ )); do
        printf '   %s. %b\n' "$((i+1))" "${available_profiles[$i]}"
    done
}

function CreateDiskImg() {
    local img="${1}"
    local format="${2}"
    local size="${3}"
    [[ "${img}" == *.* ]] || img="${img}.${format}"
    qemu-img create -f "${format:-"raw"}" "${img}" "${size:-"20G"}"
    log info "Disk created:"
    printf '    %s %-4s = %s\n' \
        "Disk image:  "  ""  "${img}" \
        "Disk size:   "  ""  "${size:-"20G"}" \
        "Disk format: "  ""  "${format:-"raw"}"
}

function WriteProfile() {
    local config_file="${1}"
    local profile_name="${2:-"default"}"
    local img="${3:-""}"
    local iso="${4:-""}"
    local comment="${5:-""}"
    local msg="${profile_name^}"
    [[ -n "${comment}" ]] && msg+=": ${comment^}"
    mapfile -t available_profiles < <(grep -o '^[A-Za-z_]*=(' "${config_file}" | sed 's/=(//')
    for ((i=0;i<${#available_profiles[@]};i++)); do
        if [[ "${profile_name}" == "${available_profiles[$i]}" ]]; then
            return 1
        fi
    done

    [[ -s "${config_file}" ]] || printf '%s\n' '#!/usr/bin/env bash' 1> "${config_file}"
    if cat >> "${config_file}" << EOF

# ${msg}
${profile_name}=(
    # Disk image
    "${img}"

    # ISO file
    "${iso}"
)

EOF
    then
        log info "New profile added: Profile: '${profile_name}'"
    else
        log info "Failed to add profile: Profile: '${profile_name}'"
    fi
    return 0
}

function print_row() {
    local label="$1"
    local value="$2"
    printf "  %b%-16b%b: %b\n" "$MSG_COL" "$label" "${NC}" "$value"
}

# Boot VM with ISO
function boot_VM() {
    local img="$1"
    local iso="$2"
    local format="$3"
    local -i ram=$4
    local -i full_scr=$5
    local profile_in_use="$6"
    local ram_display=""

    local -a qemu_flags_arr=(
        "-m" "${ram}"
        "-cpu" "EPYC-v4"
        "-vga" "qxl"
        "-display" "gtk,gl=on,show-menubar=off,zoom-to-fit=on"
        "-boot" "d"
        "-enable-kvm"
        "-drive" "file=${disk_img// /\\},media=disk,format=${format},if=virtio"
        "-drive" "file=${iso// /\\},media=cdrom"
    )

    [[ $full_scr -eq 1 ]] && qemu_flags_arr+=( "-full-screen" )

    if (( ram >= 1024 )); then
        ram_display="$(awk -v mb="$ram" 'BEGIN { printf "%.2f GB", mb / 1024 }')"
    else
        ram_display="${ram} MB"
    fi

    printf "${HL}Booting VM: Disk + ISO${NC}\n"
    print_row "Profile"         "${profile_in_use}"
    print_row "Disk file"       "${BLUE}${img}${NC}"
    print_row "ISO file"        "${BLUE}${iso}${NC}"
    print_row "Disk format"     "${format}"
    print_row "RAM Allocated"   "${ram_display}"

    qemu-system-x86_64 "${qemu_flags_arr[@]}" & disown
}

# Start VM from disk
function start_VM() {
    local img="$1"
    local format="$2"
    local -i ram=$3
    local -i full_scr=$4
    local profile_in_use="$5"
    local ram_display=""

    local -a qemu_flags_arr=(
        "-m" "${ram}"
        "-cpu" "EPYC-v4"
        "-vga" "qxl"
        "-display" "gtk,gl=on,show-menubar=off"
        "-enable-kvm"
        "-audiodev" "pa,id=devpa"
        "-drive" "file=${img// /\\},media=disk,format=${format},if=virtio"
    )

    [[ $full_scr -eq 1 ]] && qemu_flags_arr+=( "-full-screen" )

    if (( ram >= 1024 )); then
        ram_display="$(awk -v mb="$ram" 'BEGIN { printf "%.2f GB", mb / 1024 }')"
    else
        ram_display="${ram} MB"
    fi

    printf "${HL}Starting VM: Disk only${NC}\n"
    print_row "Profile"         "${profile_in_use}"
    print_row "Disk file"       "${BLUE}${img}${NC}"
    print_row "Disk format"     "${format}"
    print_row "RAM Allocated"   "${ram_display}"

    qemu-system-x86_64 "${qemu_flags_arr[@]}" & disown
}

# Helper functions

function set_value() {
    local -n var_ref=${1}
    local -n value_ref=${2}
    [[ -n "${value_ref}" ]] || { log error "'${var_ref}' requires a value"; return 1; }
    var_ref="${value_ref}"
}

function set_profile() {
    local -n var_ref=${1}
    local -n value_ref=${2}
    [[ -n "${value_ref}" ]] || { log error "'${var_ref}' requires a value"; return 1; }
    var_ref+=("${value_ref}")
}


function resolve_path() {
    local file="${1}" profile="${2}"
    if [[ "${file}" == */* ]]; then
        printf '%s\n' "${file}"
    else
        printf '%s\n' "${CONFIG_DIR}/${profile}/${file}"
    fi
}

function require() {
    local var="${1:-""}" _type="${2:-""}" msg="${3:-""}"
    [[ -n "${var}" ]] && return 0
    if [[ -n "${msg}" ]]; then
        log "${_type}" "${msg}"; return 1
    else
        return 1
    fi
}

function require_file() {
    local file="${1}" msg="${2}"
    [[ -f "${file}" ]] || \
        { log error "${msg}"; return 1; }
}

function main() {
    local -a args=("$@")

    local disk_img="" iso_img="" disk_format=""
    local -g CONFIG_DIR="${HOME}/.config/custom/vmctl"
    local -a profile_names=()
    local -a requested_profiles=()
    local config_file="${CONFIG_DIR}/profiles"
    local comment="" new_image_path=""

    local -i boot=0 full_scr=0
    local -i ram="$(( $(awk '/MemTotal/ { print $2 }' /proc/meminfo) / 1640 ))"
    local -i should_create_profile=0 should_create_img=0
    local disk_size=""

    [[ ${#args[@]} -eq 0 ]] && {
        Usage "${config_file}"
        return 0
    }

    mkdir -p "${CONFIG_DIR}"

    if ! require_file "${config_file}" "Config '${config_file}' not found"; then
        WriteProfile "${config_file}"
    fi

    # shellcheck disable=SC1090
    source "${config_file}"

    # Parse args
    local arg="" value=""
    for ((i=0;i<${#args[@]};i++)); do
        arg="${args[$i]}"
        [[ "${args[$((i+1))]:-""}" && "${args[$((i+1))]:-""}" != -* ]] && \
            value="${args[$((i+1))]:-""}" i=$((i+1))
        if [[ "${arg}" == *=* ]]; then
            IFS=$'=' read -r arg value <<< "${arg}"
            [[ -n "${value}" ]] || \
                { log error "'${arg}' requires a value"; return 1; }
        fi
        [[ "${arg}" == --* ]] && arg="${arg//--/-}"
        case "${arg}" in
            -b|-boot)           boot=1                                      ;;
            -f|-full*)          full_scr=1                                  ;;
            -image|-*image)     set_value disk_img value                    ;;
            -iso|-*iso)         set_value iso_img value                     ;;
            -ram|-*ram)         set_value ram value                         ;;
            -comm*)             set_value comment value                     ;;
            -for*)              set_value disk_format value                 ;;
            -p|-profile*)       set_profile profile_names value              ;;
            -l|-list*)          ListProfiles "${config_file}"; return 0     ;;
            -e|-edit*)          EditConfigFile "${config_file}"; return 0   ;;
            -h|-help)           Usage "${config_file}"; return 0            ;;
            -create*ima*)
                IFS=$',' read -r new_image_path disk_format disk_size <<< "${value}"
                require "${new_image_path}" error "No image specified" && should_new_image_path=1
                require "${disk_format}" "" "" || disk_format="${new_image_path##*.}"
                [[ "${disk_size}" =~ ^[0-8]+(K|M|G)$ ]] || { log error "size not in K|M|G suffix"; return 1; }
                ;;
            -create*pro*|-new*pro*)
                set_profile profile_names value
                should_create_profile=1
                ;;
            [A-Za-z_]*)
                if declare -p "${arg}" 2> /dev/null | grep -q 'declare -a'; then
                    requested_profiles+=("${arg}")
                else
                    log fatal "'${arg}' Not a valid profile"
                fi
                ;;
            *)
                log warn "Unknown argument: '${arg}'"
                Usage "${config_file}"
                return 1
                ;;
        esac
    done

    if [[ ${#profile_names[@]} -eq 0 ]]; then
        log error "No profile given"
        return 1
    fi

    for profile in "${profile_names[@]}"; do
        IFS=',' read -r -a parts <<< "${profile}"
        requested_profiles+=("${parts[@]}")
    done

    for req_profile in "${requested_profiles[@]}"; do

        new_image_path="$(resolve_path "${new_image_path}" "${req_profile}")"

        if [[ $should_create_img -eq 1 ]]; then
            require "${req_profile}" fatal "No profile name specified"
            require "${new_image_path}" fatal "No disk image specified"
            require "${disk_format}" fatal "No disk format specified"
            require "${disk_size}" fatal "No image size specified"
            [[ "${disk_size}" == "0" ]] && log fatal "Invalid disk size"
            mkdir -p "${CONFIG_DIR}/${req_profile}"
            CreateDiskImg "${new_image_path}" "${disk_format}" "${disk_size}"
            return 0
        fi

        if [[ $should_create_profile -eq 1 ]]; then
            local temp_iso_img="" temp_create_img=""
            require "${iso_img}" warn "No ISO image is given"
            temp_iso_img="$(resolve_path "${iso_img}" "${req_profile}")"
            require "${disk_img}" fatal "No disk image is given"
            temp_iso_img="$(resolve_path "${disk_img}" "${req_profile}")"

            WriteProfile \
                "${config_file}" \
                "${req_profile}" \
                "${disk_img:-"${temp_create_img}"}" \
                "${iso_img:-"${temp_iso_img}"}" \
                "${comment}" || \
                log warn "'${req_profile}' already exists"
            return 0
        fi

        if [[ ${#requested_profiles[@]} -eq 0 ]]; then
            require "${req_profile}" fatal "No profile name was given"
        fi

        # shellcheck disable=SC1090
        source "${config_file}"

        load_profile "${req_profile}" disk_img iso_img disk_format

        require "${disk_format}" "" "" || disk_format="${iso_img#*.}"
        require "${disk_format}" error "Disk format not set"

        require "${disk_img}" error "Disk image not set"
        require_file "${disk_img}" error "Disk image path '${BLUE}${disk_img}${NC}' is invalid"

        [[ $boot -eq 1 ]] && require "${iso_img}" error "Disk image not set"
        [[ $boot -eq 1 ]] && require_file "${iso_img}" error "No ISO image given"

        # Launch VM
        if [[ $boot -eq 1 ]]; then
            boot_VM \
                "${disk_img}" \
                "${iso_img}" \
                "${disk_format}" \
                $ram \
                $full_scr \
                "${req_profile}"
        else
            start_VM \
                "${disk_img}" \
                "${disk_format}" \
                $ram \
                $full_scr \
                "${req_profile}"
        fi
    done
}

main "$@"

