#!/usr/bin/env bash

set -euo pipefail

# Global Colors
HL="\033[1m"
NC="\033[0m"
MSG_COL="\033[38;2;255;240;200m"
BLUE="\033[38;2;116;112;218m"

# Log function
function log() {
    local _type="${1}"; shift
    local _color="" _t=""
    local -g info_color="\033[38;2;85;255;126m" \
        warn_color="\033[38;2;255;170;10m" \
        error_color="\033[38;2;244;29;31m" \
        fatal_color="\033[5m\033[38;2;255;0;0m" \
        other_color="\033[38;2;251;255;208m" \
        nc="\033[0m"
    case "${_type}" in
        info) _color="${info_color}" _t="*" ;;
        warn) _color="${warn_color}" _t="^" ;;
        error) _color="${error_color}" _t="!" ;;
        fatal) _color="${fatal_color}" _t="#" ;;
        *) _color="${other_color}" _t="" ;;
    esac

    printf "[%b%s%b%s]: %b\n" "${_color}" "${_type}" "${nc}" "${_t}" "${*}"
}


# Usage message
function Usage() {
    local config_file="${1}"
    local script_basename="${0##*/}"
    printf '\n%b\n' "${HL}Usage${NC}: ${script_basename} [boot] [options] <profile1> <profile2> ...\n"
    printf "  ${MSG_COL}%-18b${NC} %b\n" \
        "boot"              "Boot from ISO + disk image" \
        "<profile>"         "Profile name (defined in $(ColorPath "${config_file}"))" \
        "-f, fullscreen"    "Enable fullscreen mode" \
        "-e, edit"          "Edit the profiles config file"

    printf "\n${HL}Other flags:${NC}\n"
    printf "  ${MSG_COL}%-18b${NC} %b\n" \
        "create-image"      "Create new disk image" \
        "format"            "Specify the disk format when creating a new image" \
        "new-profile"       "Add a new profile to $(ColorPath "${config_file}") configuration" \
        "write"             "Write the current arugment values to the configuration" \
        "comment"           "Provide a comment when creating a new profile" \
        "-h, help"          "Show this help message"

    printf "\n${HL}Examples:${NC}\n"
    printf "  %s\n     ${HL}%b${NC}\n" \
        "Start with disk only"          "${script_basename} my_profile" \
        "Boot with Disk + ISO"          "${script_basename} boot my_profile" \
        "Create new image"              "${script_basename} profile=my_profile create-new-image image_name raw 20G" \
        "Create new profile"            "${script_basename} create-profile my_profile iso=/path/to/ISO.iso img=/path/to/disk.img"
    printf '%s\n' ""
}

function load_profile() {
    local profile_name="$1"
    local -n disk_img_=$2
    local -n iso_img_=$3
    local -n disk_format_=$4
    local -n selected_profile=${profile_name}

    if ! declare -p "${profile_name}" 2> /dev/null | grep -q 'declare -a' ; then
        log fatal "Profile '${profile_name}' not found."
        return 1
    fi

    for n in "${selected_profile[@]}"; do
        [[ "${n}" != *=* ]] && { log error "invalid pair '${n}'"; return 1; }
        IFS=$'=' read -r key value "${n}"
        case "${key}" in
            img) disk_img_+=("${value}") ;;
            iso) iso_img_="${value}" ;;
        esac
    done
    disk_img_="${selected_profile[0]}"
    iso_img_="${selected_profile[1]:="No_ISO"}"
    disk_format_="${disk_img_##*.}"
}

function EditConfigFile() {
    local file="$1"
    ${EDITOR:-vim} "${file}"
}

function ColorPath() {
    sed "s@${HOME}@${BLUE//\\/\\\\}~${NC//\\/\\\\}@g" <(printf "%s\n" "${1}")
}

function ListProfiles() {
    local config_file="$1"
    local -a available_profiles=""
    [[ -f "${config_file}" ]] || return 1
    log info "Available profiles in $(ColorPath "${config_dir}"):"
    mapfile -t available_profiles < <(grep -o '^[A-Za-z_]*=(' "${config_file}" | sed 's/=(//')
    for (( i=0; i < ${#available_profiles[@]}; i++ )); do
        printf '   %s. %b\n' "$((i+1))" "${available_profiles[$i]}"
    done
}

function CreateDiskImg() {
    local img="$1"
    local format="$2"
    local size="$3"
    [[ "${img}" == *.* ]] || img="${img}.${format}"
    qemu-img create -f ${format:-"raw"} "${img}" "${size:-"20G"}"
    log info "Disk created:"
    printf '    %s %-4s = %s\n' \
        "Disk image:  "  ""  "${img}" \
        "Disk size:   "  ""  "${size:-"20G"}" \
        "Disk format: "  ""  "${format:-"raw"}"
}

function WriteProfile() {
    local config_file="${1}"
    local profile_name="${2:-"default"}"
    local img="${3:-""}"
    local iso="${4:-""}"
    local comment="${5:-""}"
    local msg="${profile_name^}"
    [[ -n "${comment}" ]] && msg+=": ${comment^}"
    mapfile -t available_profiles < <(grep -o '^[A-Za-z_]*=(' "${config_file}" | sed 's/=(//')
    for ((i=0;i<${#available_profiles[@]};i++)); do
        if [[ "${profile_name}" == "${available_profiles[$i]}" ]]; then
            return 1
        fi
    done

    [[ -s "${config_file}" ]] || printf '%s\n' '#!/usr/bin/env bash' 1> "${config_file}"
    if cat >> "${config_file}" << EOF

# ${msg}
${profile_name}=(
    # Disk image
    "${img}"

    # ISO file
    "${iso}"
)

EOF
    then
        log info "New profile added: Profile: '${profile_name}'"
    else
        log info "Failed to add profile: Profile: '${profile_name}'"
    fi
    return 0
}

function print_row() {
    local label="$1"
    local value="$2"
    printf "  %b%-16b%b: %b\n" "$MSG_COL" "$label" "${NC}" "$value"
}

# Boot VM with ISO
function boot_VM() {
    local img="$1"
    local iso="$2"
    local format="$3"
    local -i ram=$4
    local -i full_scr=$5
    local profile_in_use="$6"
    local ram_display=""

    local -a qemu_flags_arr=(
        "-m" "${ram}"
        "-cpu" "EPYC-v4"
        "-vga" "qxl"
        "-display" "gtk,gl=on,show-menubar=off,zoom-to-fit=on"
        "-boot" "d"
        "-enable-kvm"
        "-drive" "file="${disk_img// /\\}",media=disk,format="${format}",if=virtio"
        "-drive" "file="${iso// /\\}",media=cdrom"
    )

    [[ $full_scr -eq 1 ]] && qemu_flags_arr+=( "-full-screen" )

    if (( ram >= 1024 )); then
        ram_display="$(awk -v mb="$ram" 'BEGIN { printf "%.2f GB", mb / 1024 }')"
    else
        ram_display="${ram} MB"
    fi

    printf "${HL}Booting VM: Disk + ISO${NC}\n"
    print_row "Profile"         "${profile_in_use}"
    print_row "Disk file"       "${BLUE}${img}${NC}"
    print_row "ISO file"        "${BLUE}${iso}${NC}"
    print_row "Disk format"     "${format}"
    print_row "RAM Allocated"   "${ram_display}"

    qemu-system-x86_64 "${qemu_flags_arr[@]}" & disown
}

# Start VM from disk
function start_VM() {
    local img="$1"
    local format="$2"
    local -i ram=$3
    local -i full_scr=$4
    local profile_in_use="$5"
    local ram_display=""

    local -a qemu_flags_arr=(
        "-m" "${ram}"
        "-cpu" "EPYC-v4"
        "-vga" "qxl"
        "-display" "gtk,gl=on,show-menubar=off"
        "-enable-kvm"
        "-audiodev" "pa,id=devpa"
        "-drive" "file=${img// /\\},media=disk,format=${format},if=virtio"
    )

    [[ $full_scr -eq 1 ]] && qemu_flags_arr+=( "-full-screen" )

    if (( ram >= 1024 )); then
        ram_display="$(awk -v mb="$ram" 'BEGIN { printf "%.2f GB", mb / 1024 }')"
    else
        ram_display="${ram} MB"
    fi

    printf "${HL}Starting VM: Disk only${NC}\n"
    print_row "Profile"         "${profile_in_use}"
    print_row "Disk file"       "${BLUE}${img}${NC}"
    print_row "Disk format"     "${format}"
    print_row "RAM Allocated"   "${ram_display}"

    qemu-system-x86_64 "${qemu_flags_arr[@]}" & disown
}

function main() {
    # Flags
    local -a arg_array=("$@")

    local disk_img="" iso_img="" disk_format=""
    local -a requested_profiles=()
    local -g config_dir="${HOME}/.config/custom/vmctl"
    local config_file="${config_dir}/profiles" profile_name=""
    local comment="" create_img=""

    local -i boot=0 full_scr=0
    local -i ram="$(( $(awk '/MemTotal/ { print $2 }' /proc/meminfo) / 1640 ))"
    local -i should_create_profile=0 should_create_img=0
    local disk_size=""

    [[ ${#arg_array[@]} -eq 0 ]] && {
        Usage "${config_file}"
        return 0
    }

    mkdir -p "${config_dir}"

    if [[ -s "${config_file}" && -f "${config_file}" ]]; then
        source "${config_file}"
    else
        log warn "No profile found. Creating a default"
        if WriteProfile "${config_file}"; then
            log info "New default profile created at '$(ColorPath "${config_file}")'"
        fi
    fi

    set_value() {
        local -n var_ref=${1}
        local -n value_ref=${2}
        [[ -n "${value_ref}" ]] || { log error "'${var_ref}' requires a value"; return 1; }
        var_ref="${value_ref}"
    }

    # Parse args
    for arg in "${arg_array[@]}"; do
        if [[ "${arg}" == *=* ]]; then
            IFS=$'=' read -r arg value <<< "${arg}"
            [[ -n "${value}" ]] || { log error "'${arg}' requires a value"; return 1; }
        fi
        case "${arg}" in
            boot|-*boot) boot=1 ;;
            image|-*image) set_value disk_img value ;;
            iso|-*iso) set_value iso_img value ;;
            ram|-*ram) set_value ram value ;;
            comm*) set_value comment value ;;
            for*) set_value disk_format value ;;
            pro*|-*pro*) set_value profile_name value ;;
            -f|-*full*|*full*) full_scr=1 ;;
            -*l|list*|-*list*) ListProfiles "${config_file}" return 0 ;;
            edit|-*edit) EditConfigFile "${config_file}" return 0 ;;
            h|-h|-*help|help) Usage "${config_file}" return 0 ;;
            create*im*|-*create*im*)
                IFS=$',' read -r create_img disk_format disk_size <<< "${value}"

                # Image file
                [[ -n "${create_img}" ]] && should_create_img=1 || { log fatal "No image specified"; return 1; }

                # Disk format
                case "${disk_format}" in
                    raw|qcow2) set_value disk_format value ;;
                    *) log error "Unknown format" ;;
                esac

                if [[ -z "${disk_format}" ]]; then disk_format="${create_img##*.}"
                else disk_format="${disk_format}"
                fi

                # Disk size
                if [[ "${disk_size}" =~ ^[0-8]+(K|M|G)$ ]]; then
                    disk_size="${disk_size}"
                fi
                ;;
            new*pro*|create*pro*|pro*|-*create*pro*|-*new*pro*)
                set_value profile_name value
                [[ -z "${profile_name}" ]] && log fatal "No profile specified"
                should_create_profile=1
                ;;
            [A-Za-z_]*)
                if declare -p "${arg}" 2> /dev/null | grep -q 'declare -a'; then
                    requested_profiles+=("${arg}")
                else
                    log fatal "'${arg}' Not a valid profile"
                fi
                ;;
            *)
                log warn "Unknown argument: '${arg}'"
                Usage "${config_file}"
                return 1
                ;;
        esac
    done

    if [[ -n "${profile_name}" ]]; then
        requested_profiles+=("${profile_name}")
    fi

    if [[ $should_create_img -eq 1 ]]; then
        [[ -z "${profile_name}" ]] && log fatal "No profile name specified"
        [[ -z "${create_img}" ]] && log fatal "No disk image specified"
        [[ -z "${disk_format}" ]] &&  log fatal "No disk format specified"
        [[ -z "${disk_size}" || "${disk_size}" == "0" ]] && log fatal "No image size specified"
        mkdir -p "${config_dir}/${profile_name}"
        CreateDiskImg "${config_dir}/${profile_name}/${create_img}" "${disk_format}" "${disk_size}"
        return 0
    fi

    if [[ $should_create_profile -eq 1 ]]; then
        local temp_iso_img="" temp_create_img=""
        if [[ -z "${iso_img}" ]]; then
            log warn "No ISO image is given"
            temp_iso_img=""
        elif [[ "${iso_img}" != */* ]]; then
            temp_iso_img="${config_dir}/${profile_name}/${iso_img}"
        else
            temp_iso_img="${iso_img}"
        fi

        if [[ -z "${disk_img}" ]]; then
            log fatal "No disk image is given"
        elif [[ "${disk_img}" != */* ]]; then
            temp_iso_img="${config_dir}/${profile_name}/${disk_img}"
        else
            temp_iso_img="${iso_img}"
        fi

        if [[ "${config_dir}/${profile_name}/${create_img}" ]]; then
            temp_create_img="${config_dir}/${profile_name}/${create_img}"
        fi

        WriteProfile "${config_file}" "${profile_name}" "${disk_img:-"${temp_create_img}"}" "${iso_img:-"${temp_iso_img}"}" "${comment}" || \
            log warn "'${profile_name}' already exists"
        [[ $? -eq 0 ]] && return 0 || return 1
    fi

    if [[ ${#requested_profiles[@]} -eq 0 ]]; then
        [[ -n "${profile_name}" ]] || log fatal "No profile name was given"
    fi

    source "${config_file}"

    for req_profile in "${requested_profiles[@]}"; do

        [[ -z "${disk_format}" ]] && disk_format="${iso_img#*.}"

        [[ -n ${iso_img} ]] && boot=1

        if [[ -z "${disk_img}" || -z "${iso_img}" || -z "${disk_format}" ]]; then
            load_profile "${req_profile}" disk_img iso_img disk_format
        fi

        # Path checks for disk image
        if [[ -z "${disk_img}" ]]; then
            log fatal "No disk image given"
        elif [[ ! -s "${disk_img}" || ! -f "${disk_img}" ]]; then
            log fatal "Disk image '${BLUE}${disk_img}${NC}' does not exist; Update it\n"
        fi

        if [[ $boot -eq 1 ]]; then
            # Path checks for iso image
            if [[ -z "${iso_img}" ]]; then
                log fatal "No ISO image given"
            elif [[ ! -s "${iso_img}" || ! -f "${iso_img}" ]]; then
                log fatal "ISO '${BLUE}${iso_img}${NC}' does not exist"
            fi
        fi

        # Entry logic
        if [[ $boot -eq 1 ]]; then
            boot_VM "${disk_img}" "${iso_img}" "${disk_format}" $ram $full_scr "${req_profile}"
        else
            start_VM "${disk_img}" "${disk_format}" $ram $full_scr "${req_profile}"
        fi
    done
}

main "$@"

