#!/usr/bin/env bash

builtin set -euo pipefail

function process_args() {
    local -a args_array=("${@}")

    local var="" fish="" dish="" maze="" dinner=""

    local arg="" value=""
    for arg in "${args_array[@]}"; do
        if [[ "${arg}" == *=* ]]; then
            IFS=$'=' read -r arg value <<< "${arg}"
            [[ -n "${value}" ]] || # Error: '${arg}' requires a value
        fi
        case "${arg}" in
            var*) var="${value}" ;;
            fish*) fish="${value}" ;;
            dish*) dish="${value}" ;;
            maze*) maze="${value}" ;;
            dinner*) dinner="${value}" ;;
            *)
                # Error: Invalid argument: "${arg}"
                # Error: use --arg=value or arg=value like pairs avoid --arg value
                ;;
        esac
    done
}

function main() {
}

main "${@}"

