#!/usr/bin/env bash

TEMP_FILE="/tmp/.cava_instances.tmp"
speed=0.02

function KILL_CAVA() {
    local -a pids=()
    mapfile -t pids < <(cat "${TEMP_FILE}")
    for pid in "${pids[@]}"; do
        kill -SIGTERM "${pid}"
    done
}

function CAVA() {
    for (( i=0 ; i < 6 ; i++ )); do
        footclient -e "cava" &>/dev/null &
        echo "$!" >> "${TEMP_FILE}"
        sleep "$speed"
        disown
    done
}

function main() {
    local flag="${1}"
    local foot_sock="${XDG_RUNTIME_DIR}/foot${WAYLAND_DISPLAY/#/-}.sock"

    [[ -S "${foot_sock}" ]] || foot --server="${foot_sock}" & disown

    [[ "${flag}" =~ ^(CLEAN|clean|KILL|kill)$ ]] && {
        KILL_CAVA || return 1
        rm -f "${TEMP_FILE}"
        return 0
    }
    CAVA
}

main "$@"

