#!/usr/bin/bash

set -o pipefail

function log() {
    local type_="${1}"; shift 1
    printf '[%s]: %s\n' "${type_}" "${*}"
}

function Usage() {
    cat << EOF

    Usage: ${0##*/} --install [sway|hyprland]

    Desc:
        Configure dbus session and starts pipewire
        Run script from tty (/usr/local/bin/[LaunchSway|LaunchHyprland])

EOF
}

function InstallSwayLauncher() {
    local script_path="${1}"
    local desktop_session_file_path="${2}"
    sudo mkdir -p "${script_path%/*}"

# Install Script
    if sudo tee "${script_path}" &>/dev/null << EOF
#!/usr/bin/env sh

cd ~ || exit 1

kill_processes() {
    pkill -u "\$(id -u)" -f 'pipewire|wireplumber|pipewire-pulse|cava -p|socat -u UNIX' 2> /dev/null
}

kill_processes

XDG_SESSION_TYPE=wayland
XDG_CURRENT_DESKTOP=sway
XDG_DESKTOP_SESSION=sway
XDG_RUNTIME_DIR=/run/user/"\$(id -u)"
PIPEWIRE_RUNTIME_DIR=/run/user/"\$(id -u)"
QT_QPA_PLATFORMTHEME=qt6ct
WLR_RENDERER=vulkan

DBUS_SOCKET_ADDR="\${XDG_RUNTIME_DIR}/dbus-sway"

pkill -u "\$(id -u)" -f "dbus-daemon --session .* --address=unix:path=\${DBUS_SOCKET_ADDR}" &
wait \$!
stat -c '%F' "\${DBUS_SOCKET_ADDR}" | grep socket 1> /dev/null 2>&1 || \\
    DBUS_SOCKET="\$(dbus-daemon --session --fork --nopidfile --print-address=1 --address=unix:path="\${DBUS_SOCKET_ADDR}")"

DBUS_SESSION_BUS_ADDRESS="\${DBUS_SOCKET}"

set -- "--config" "\${HOME}/.config/sway/config"

lsmod | grep nvidia 1> /dev/null 2>&1 && set -- "\${@}" "--unsupported-gpu"

export XDG_DESKTOP_SESSION XDG_RUNTIME_DIR XDG_SESSION_TYPE \\
    XDG_CURRENT_DESKTOP DBUS_SESSION_BUS_ADDRESS \\
    PIPEWIRE_RUNTIME_DIR QT_QPA_PLATFORMTHEME WLR_RENDERER

pipewire 1> /dev/null 2>&1 & sleep 0.4

# shellcheck disable=SC2093
exec sway "\${@}"

kill_processes

EOF
    then
        sudo chown root:root "${script_path}" && \
            sudo chmod 755 "${script_path}"
        log info "Installed script: '${script_path}'"
    fi

# Install Desktop session file
    if sudo tee "${desktop_session_file_path}" &>/dev/null << EOF
[Desktop Entry]
Name=Sway (Sway Compositor (custom))
Comment=An i3 like Wayland compositor
Exec=${script_path}
Type=Application

EOF
    then
        log info "Installed desktop session file '${desktop_session_file_path}'"
        sudo chown root:root "${desktop_session_file_path}" && \
            sudo chmod 644 "${desktop_session_file_path}"
    fi
}


function InstallHyprlandLauncher() {
    local script_path="${1}"
    local desktop_session_file_path="${2}"
    sudo mkdir -p "${script_path%/*}"

# Install script
    if sudo tee "${script_path}" &>/dev/null << EOF
#!/usr/bin/env sh

cd ~ || exit 1

kill_processes() {
    pkill -u "\$(id -u)" -f 'pipewire|wireplumber|pipewire-pulse|cava -p|socat -u UNIX' 2> /dev/null
}

kill_processes

XDG_SESSION_TYPE=wayland
XDG_RUNTIME_DIR=/run/user/"\$(id -u)"
PIPEWIRE_RUNTIME_DIR=/run/user/"\$(id -u)"
QT_QPA_PLATFORMTHEME=qt6ct
WLR_RENDERER=vulkan

DBUS_SOCKET_ADDR="\${XDG_RUNTIME_DIR}/dbus-Hyprland"

pkill -u "\$(id -u)" -f "dbus-daemon --session .* --address=unix:path=\${DBUS_SOCKET_ADDR}" &
wait \$!
stat -c '%F' "\${DBUS_SOCKET_ADDR}" | grep socket 1> /dev/null 2>&1 || \\
    DBUS_SOCKET="\$(dbus-daemon --session --fork --nopidfile --print-address=1 --address=unix:path="\${DBUS_SOCKET_ADDR}")"

DBUS_SESSION_BUS_ADDRESS="\${DBUS_SOCKET}"

set -- "--config" "\${HOME}/.config/hypr/hyprland.conf"

export XDG_SESSION_TYPE XDG_RUNTIME_DIR \\
    PIPEWIRE_RUNTIME_DIR QT_QPA_PLATFORMTHEME \\
    WLR_RENDERER DBUS_SESSION_BUS_ADDRESS

pipewire 1> /dev/null 2>&1 & sleep 0.4

exec Hyprland "\${@}"

EOF
    then
        sudo chown root:root "${script_path}" && \
            sudo chmod 755 "${script_path}"
        log info "Installed script: '${script_path}'"
    fi

# Install Desktop session file
    if sudo tee "${desktop_session_file_path}" &>/dev/null << EOF
[Desktop Entry]
Name=Hyprland (Hyprland Compositor (custom))
Comment=Hyprland - dynamic tiling window manager
Exec=${script_path}
Type=Application

EOF
    then
        sudo chown root:root "${desktop_session_file_path}" && \
            sudo chmod 644 "${desktop_session_file_path}"
        log info "Installed desktop session file '${desktop_session_file_path}'"
    fi
}

function main() {
    local args=("${@}")

    local arg="" value=""
    for ((i=0;i<${#args[@]};i++)); do
        arg="${args[$i]}"
        [[ -n "${args[$((i+1))]:-""}" && "${args[$((i+1))]:-""}" != -* ]] && \
            value="${args[$((i+1))]:-""}" i=$((i+1))
        [[ "${arg}" == --* ]] && arg="${arg//--/-}"
        if [[ "${arg}" == "-install" ]]; then
            [[ "${value}" == sway ]] && \
                InstallSwayLauncher \
                    "/usr/local/bin/LaunchSway" \
                    "/usr/share/wayland-sessions/custom_sway.desktop"
            [[ "${value}" == hyprland ]] && \
                InstallHyprlandLauncher \
                    "/usr/local/bin/LaunchHyprland" \
                    "/usr/share/wayland-sessions/custom_hyprland.desktop"
        fi
        [[ "${arg}" =~ ^(-help|-h)$ ]] && Usage
    done
}

main "${@}"

