#!/usr/bin/env bash

# set -euo pipefail

IFS=$' \n'

readonly RED="\033[38;2;244;10;10m" \
    GREEN="\033[38;2;161;239;116m" \
    WARN="\033[38;2;233;98;116m" \
    BROWN="\033[38;2;240;120;120m" \
    LIGHT_SKIN="\033[38;2;255;230;180m" \
    MUDDY="\033[38;2;195;158;151m" \
    GREY="\033[38;2;160;160;140m" \
    BLUE="\033[38;2;150;134;255m" \
    NC="\033[0m"

declare -a  MPV_FLAGS=()
declare -a SELECTED=() CURRENTLY_PLAYING=()

QUIET=0
DETACH=0

readonly MUSIC_DIR="${HOME}/Media/Music"

function LOG() {
    local type_="${1}"; shift
    case "${type_}" in
        info)
            [[ "${QUIET}" -eq 0 ]] && \
                { printf "[%b*%b]: " "${GREEN}" "${NC}"; printf "%b" "${*}\n"; }
            ;;
        cmd_info)
            [[ "${QUIET}" -eq 0 ]] && \
                { printf "[%b%s%b]: " "${GREEN}" "${type_}" "${NC}"; \
                    for m in "${@}"; do printf '%b ' "${m}"; done; printf '\n'; }
            ;;
        warn) printf '[%b%s%b]: %b\n' "${WARN}" "^" "${NC}" "${*}" ;;
        error) printf '[%b%s%b]: %b\n' "${RED}" "!" "${NC}" "${*}" ;;
    esac
}

function Usage() {
    printf "%b\n" \
        "" \
        " ${MUDDY}Usage:${NC} PlayMusic [OPTIONS]" \
        "" \
        " ${MUDDY}Options:${NC}" \
        "   -vid, --video           Enable video output (default: no)" \
        "   -vol=N, --volume=N      Set volume (default: 65)" \
        "   -q, --quiet             Suppress MPV output" \
        "   -s, --shuffle           Shuffle selected tracks (only with --loop)" \
        "" \
        " ${MUDDY}Behavior:${NC}" \
        "   * Uses ${BLUE}fzf${NC} to pick music from '${LIGHT_SKIN}$(ColorPath "${MUSIC_DIR}")${NC}'" \
        "   * Supports all major audio formats" \
        "   * Applies optimized mpv flags (hardware decoding, mpris, hdr, etc.)" \
        "" \
        " ${MUDDY}Examples:${NC}" \
        "   PlayMusic                   # Launch, pick music, play (loop-playlist)" \
        "   PlayMusic --shuffle         # Random shuffle" \
        "   PlayMusic --vol=45          # Set volume to 45" \
        "" \
        " ${BROWN}Note:${NC} Shuffle does nothing without multiple files & --loop." \
        ""
}

function ColorPath() {
    sed "s@${HOME}@${BLUE//\\/\\\\}~${NC//\\/\\\\}@g" <(printf '%s\n' "${1}")
}

function Exit() {
    if [[ $1 =~ ^[0-9]+$ || -z $1 ]]; then
        exit "${1:-0}"
    else
        printf "%s\n\n" "$1"
        exit "${2:-0}"
    fi
}

function CheckDependencies() {
    local -a deps=(mpv fzf)
    local -a missing=()

    for cmd in "${deps[@]}"; do
        if ! command -v "${cmd}" &> /dev/null; then
            missing+=("${cmd}")
        fi
    done

    if [[ ${#missing[@]} -gt 0 ]]; then
        LOG error "Missing dependencies:"
        for dep in "${missing[@]}"; do
            echo -e "  - ${RED}${dep}${NC}"
        done
        echo -e "${WARN}Please install the missing dependencies and try again.${NC}"
        Exit "Exiting..." 1
    fi
}

function TurnMusicOn() {
    local -a files_joined=("$@")
    local -a quoted_files=()
    local file=""
    local track_num=0

    if [[ $ENABLE_MPV_TUI -eq 1 ]]; then
        mpv "${MPV_FLAGS[@]}" "${files_joined[@]/#/${MUSIC_DIR}/}"
    else
        LOG info "${BLUE}Tracks${NC}:"
        for ((i=0;i<${#files_joined[@]};i++)); do
            track_num=$((i+1))
            file="${files_joined[$i]}"
            quoted_files+=( "'${BLUE}$(ColorPath "${MUSIC_DIR}")/${LIGHT_SKIN}${file}${NC}'" )
            CURRENTLY_PLAYING+=( "${file##"${file%%"${file##*/}"}"}" )
            LOG info "  ${GREY}$track_num${NC} ${LIGHT_SKIN}${CURRENTLY_PLAYING[$i]%.*}${NC}"
        done
        printf '\n'
        LOG cmd_info "${BROWN}mpv${NC}" "${MPV_FLAGS[@]}" "${quoted_files[@]}"
        if [[ $DETACH -eq 1 ]]; then
            mpv "${MPV_FLAGS[@]}" "${files_joined[@]/#/${MUSIC_DIR}/}" & disown
        else
            mpv "${MPV_FLAGS[@]}" "${files_joined[@]/#/${MUSIC_DIR}/}"
        fi
        printf '\n'
    fi
}

function Play() {
    local -a music_files=()
    for file in "${SELECTED[@]}"; do
        if [[ -f "${MUSIC_DIR}/${file}" ]]; then
            music_files+=("${file}")
        else
            LOG error "No such Music file: '${LIGHT_SKIN}${file}${NC}'"
        fi
    done
    TurnMusicOn "${music_files[@]}"
}

function main() {
    local -a ARG_ARR=("$@")
    local volume="" video=""
    local -i shuffle=0 play_all=0
    local -g loop=0 ENABLE_MPV_TUI=0

    CheckDependencies

    local arg=""
    for (( i=0 ; i < ${#ARG_ARR[@]} ; i++ )); do
        arg="${ARG_ARR[$i]}"
        case "${arg}" in
            vol|--vol--volume|volume)
                volume=${ARG_ARR[ $((i+1)) ]}
                [[ -z ${volume} || ${volume} == -* ]] && {
                    LOG error "No argument give after ${GREY}--volume${NC}"
                    LOG info "Default volume: ${BLUE}65${NC}"
                    volume=65
                }
                i=$((i+1))
                ;;
            vol=*|--vol=*|--volume=*|volume=*)
                if [[ "${arg#*=}" =~ ^[0-9]+$ ]]; then
                    volume=$(awk -F'=' '{print $2}' <<< "${arg}")
                else
                    LOG error "Invalid volume: ${arg}"
                    LOG info "Default volume: ${BLUE}65${NC}"
                fi
                ;;
            vid|--vid|--video|video) video="auto" ;;
            -q|--quiet) QUIET=1 ;;
            -t|-*tui|tui) ENABLE_MPV_TUI=1 ;;
            -a|-*play*all|play*all|all) play_all=1 ;;
            -s|--shuff|shuff|--shuffle|shuffle) shuffle=1 ;;
            -d|--disown|--detach)  DETACH=1 ;;
            -h|--help|help) Usage; Exit 0 ;;
            *)
                if [[ -d "${arg}" ]];then
                    MUSIC_DIR="${arg}"
                else
                    Usage; Exit 0
                fi
                ;;
        esac
    done

    trap 'Exit 0' SIGINT SIGQUIT
    trap 'Exit 1' SIGTERM

    [[ -d "${MUSIC_DIR}" ]] || {
        LOG error "Music directory not found: '${BLUE}${MUSIC_DIR}${NC}'"
        Exit 1
    }

    if [[ $play_all -eq 1 ]]; then
        mapfile -t SELECTED < <(find "${MUSIC_DIR}" \( -type f -iregex '.*\.\(mp3\|flac\|m4a\|wav\|aac\|ogg\|opus\|wma\|alac\|ape\|mpc\|wavpack\|webm\|mp4\)' \) -printf "%P\n")
    else
        mapfile -t SELECTED < <(find "${MUSIC_DIR}" \( -type f -iregex '.*\.\(mp3\|flac\|m4a\|wav\|aac\|ogg\|opus\|wma\|alac\|ape\|mpc\|wavpack\|webm\|mp4\)' \) -printf "%P\n" | fzf --multi)
    fi

    if [[ ${#SELECTED[@]} -eq 0 ]]; then
        LOG info "No song selected"
        Exit 1
    elif [[ ${#SELECTED[@]} -gt 1 ]]; then
        loop=1
    fi

    [[ $shuffle -eq 1 && $loop -eq 0 ]] && LOG warn "Shuffle can only be used with mutiple tracks"
    [[ $shuffle -eq 1 ]] && mapfile -t SELECTED <(printf "%s\n" "${SELECTED[@]}" | shuf)

    MPV_FLAGS+=(
        "--vid=${video:-"no"}"
        "--volume=${volume:-64}"
    )

    MPV_FLAGS+=(
        "--osc=no"
        "--script-opts=mpris=yes"
    )

    if  [[ $ENABLE_MPV_TUI -eq 1 ]]; then
        MPV_FLAGS+=(
            "--vo=tct"
            "--vid=auto"
            "--really-quiet"
        )
    else
        MPV_FLAGS+=( "--vo=gpu-next")
    fi

    MPV_FLAGS+=(
        "--hwdec=vulkan"
        "--gpu-api=vulkan"
        "--hdr-compute-peak"
        "--loop-playlist=inf"
        "--msg-level=all=error"
        "--really-quiet"
    )
    [[ "${QUIET}" -eq 1 ]] && MPV_FLAGS+=("--really-quiet")

    Play
}

main "$@"

