#!/usr/bin/env bash

# Color definitions
HL="\033[1m"
NC="\033[0m"
MSG_COL="\033[38;2;255;240;200m"
RED="\033[38;2;255;0;0m"

#  Message helpers
function INFO()  { printf "%b\n" "[${HL}*${NC}] ${MSG_COL}$1${NC}"; }
function ERROR() { printf "%b\n" "[${RED}!${NC}] $1"; exit 1; }

# Usage info
function Usage() {
    printf "%b\n" \
        "${HL}Usage${NC}: $(basename "$0") [options] <YouTube-Playlist-URL>" "" \
        "${MSG_COL}Options:${NC}" \
        "  -o <dir>      Set custom output directory" \
        "  -h, --help    Show this help message" "" \
        "${MSG_COL}Example:${NC}" \
        "  $(basename "$0") -o ~/Music 'https://youtube.com/playlist?list=xyz123'" ""
    exit 0
}

function ColorPath() {
    local blue="\033[38;2;150;134;255m" nc="\033[0m"
    sed -e "s@${HOME}@${blue//\\/\\\\}~${nc//\\/\\\\}@g" <(printf "%s\n" "${1}")
}

function main() {
    # Default configuration
    local -a args=("${@}")
    local concurrent_downloads=4
    local download_directory=""
    local playlist_url="${args[$((${#args[@]}-1))]}"
    args=("${args[@]:0:$((${#args[@]}-1))}")

    # Argument parsing
    local arg="" value="" next_arg=""
    for ((i=0;i<${#args[@]};i++)); do
        arg="${args[$i]}"
        next_arg="${args[$((i+1))]:-""}"
        [[ "${next_arg}" != -* ]] && i=$((i+1)) value="${next_arg}"
        if [[ "${arg}" == *=* ]]; then
            IFS=$'=' read -r arg value <<< "${arg}"
            [[ -n "${value}" ]] || ERROR "'${arg}' requires a value"
        fi
        case "${arg}" in
            -d) download_directory="${value}" ;;
            -h|--help) Usage ;;
            *) ERROR "Unknown argument: '${arg}'" ;;
        esac
    done

    # [[ -n "${playlist_url}" ]] || ERROR "No playlist URL given."
    [[ -d "${download_directory}" ]] || ERROR "Directory ${download_directory@Q} doesn't exist."

    cd "${download_directory}" || ERROR "Cannot change directory ${download_directory@Q}"

    local -a yt_dlp_args=(
        "-f" "bestaudio"
        "-N" "${concurrent_downloads}"
        "--extract-audio"
        "--add-metadata"
        "--embed-thumbnail"
        "--yes-playlist"
        "--audio-quality" "0"
        "--audio-format" "opus"
        "--convert-thumbnails" "jpg"
        "--metadata-from-title" "%(artist)s - %(title)s"
        "-o" "%(title)s.%(ext)s"
    )

    INFO "Directory: '$(ColorPath "${download_directory}")'"
    INFO "Url: '$(ColorPath "${playlist_url}")'"
    INFO "Cmd: yt-dlp ${yt_dlp_args[*]} '$(ColorPath "${playlist_url}")'"

    yt-dlp "${yt_dlp_args[@]}" "${playlist_url}"
}

main "$@"

