#!/usr/bin/bash

set -o pipefail

function log() {
    local type_="${1}"; shift 1
    printf '[%s]: %s\n' "${type_}" "${*}"
}

function kill_processes() {
    pkill -u "${USER}" -f 'pipewire' 2> /dev/null || true
    pkill -u "${USER}" -f 'wireplumber' 2> /dev/null || true
    pkill -u "${USER}" -f 'pipewire-pulse' 2> /dev/null || true
    pkill -u "${USER}" -f 'cava -p' 2> /dev/null || true
    pkill -u "${USER}" -f 'socat -u UNIX' 2> /dev/null || true
}

function start_sway() {
    local -i num_=${1:-0}
    local -a sway_flags=()
    local -a env_vars=(
        # "LIBVA_DRIVER_NAME=radeonsi"
        "__GLX_VENDOR_LIBRARY_NAME=mesa"
        # "WLR_NO_HARDWARE_CURSORS=1"
        "XDG_SESSION_TYPE=wayland"
        "XDG_CURRENT_DESKTOP=sway"
        "XDG_DESKTOP_SESSION=sway"
        "XDG_RUNTIME_DIR=/run/user/$UID"
        "PIPEWIRE_RUNTIME_DIR=/run/user/$UID"
        "QT_QPA_PLATFORMTHEME=qt6ct"
        "WLR_RENDERER=vulkan"
    )

    if [[ ! $num_ =~ ^[0-1]$ ]]; then
        printf '%s: %s\n' error "Argument must be 0 or 1\n"
        return 1
    fi

    cd ~ || {
        printf '%s: %s\n' error "Cannot change to home directory\n"
        return 1
    }

    kill_processes

    export "${env_vars[@]}"

    grep -q nvidia <(lsmod) && sway_flags+=( --unsupported-gpu ) || true

    if exec /usr/bin/sway "${sway_flags[@]}"; then
        printf '%s: %s\n' info "Sway started successfully"
        kill_processes
        return 0
    else
        printf '%s: %s\n' error "Failed to start Sway"
    fi
}

function Install_sway_desktop() {
    set -eu
    local desktop_session_file="/usr/share/wayland-sessions/sway_custom.desktop"
    local user_script=""
    local install_file="/usr/local/bin/Sway"
    user_script="$(find ~/.bin/ -type f -name Sway)"
    [[ -s "${user_script}" ]] || { log error "No user script found in ~/.bin/"; return 1; }
    log info "Found user script at '${user_script}'"
    sudo cp -f "${user_script}" "${install_file}" && log info "Installed user script at '${install_file}'"
    sudo mkdir -p "${desktop_session_file%%/"${desktop_session_file##*/}"}" "${install_file%%/"${install_file##*/}"}"
    if sudo tee "${desktop_session_file}" &>/dev/null << EOF
[Desktop Entry]
Name=Sway (Waylan Compositor)
Comment=An i3 like Wayland compositor
Exec=dbus-run-session ${install_file}
Type=Application

EOF
    then
        sudo chmod 755 "${install_file}"
        sudo chown root:root "${install_file}"
        sudo chmod 644 "${desktop_session_file}"
        log info "New desktop file installed at '${desktop_session_file}'"
    else
        log info "Failed to install '${desktop_session_file}'"
    fi
}

function main() {
    for arg in "${@}"; do
        case ${arg} in
            -*install|install)
                Install_sway_desktop
                return $?
                ;;
        esac
    done
    start_sway "${1:-0}"
}

main "${@}"

